/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import Module.ServerConnection;
import Module.Warehouse;
import com.nitido.utils.toaster.Toaster;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jayjomjohn
 */
public class Asset_RequestForm extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
            
    public Asset_RequestForm() {
        initComponents();
        conn=ServerConnection.ConnecrDb();
        
        autoID();
    }
//==================================================================================================
   public void AssetRequest() {
            DefaultTableModel model = (DefaultTableModel) Warehouse.tableRequest.getModel(); 
        try{
            String sql ="SELECT * FROM Log1_AssetRequest";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Warehouse.tableRequest.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
             }catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }       
//==================================================================================================    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtReceiveID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtSubcat = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtRequest = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtposition = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtdept = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpurpose = new javax.swing.JTextArea();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Submit = new javax.swing.JButton();
        Requestdate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBody.setBackground(new java.awt.Color(255, 255, 255));
        PanelBody.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        PanelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        PanelBody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 520));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Request Form");
        PanelBody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 172, 40));

        Exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        PanelBody.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 40, 40));
        PanelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 380, 10));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Receive ID");
        PanelBody.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 60, 100, 30));

        txtReceiveID.setEditable(false);
        txtReceiveID.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtReceiveID.setText(" ");
        txtReceiveID.setBorder(null);
        txtReceiveID.setOpaque(false);
        PanelBody.add(txtReceiveID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 230, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Asset Category");
        PanelBody.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 100, 100, 30));

        jComboBox2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Choose here-", "Computer", "Furniture", "Stationary", "Electronics", "Others" }));
        PanelBody.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 230, 30));
        PanelBody.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 230, 10));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Sub-Category");
        PanelBody.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 140, 100, 30));

        txtSubcat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtSubcat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubcat.setText(" ");
        txtSubcat.setBorder(null);
        PanelBody.add(txtSubcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 230, 30));
        PanelBody.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 230, 10));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Request By");
        PanelBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 180, 100, 30));

        txtRequest.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtRequest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRequest.setText(" ");
        txtRequest.setBorder(null);
        PanelBody.add(txtRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 230, 30));
        PanelBody.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 230, 10));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Position");
        PanelBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 220, 100, 30));

        txtposition.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtposition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtposition.setText(" ");
        txtposition.setBorder(null);
        PanelBody.add(txtposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 230, 30));
        PanelBody.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 230, 10));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Request Date");
        PanelBody.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 300, 100, 30));

        txtdept.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtdept.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdept.setText(" ");
        txtdept.setBorder(null);
        PanelBody.add(txtdept, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 230, 30));
        PanelBody.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 230, 10));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Department");
        PanelBody.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 260, 100, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Purpose");
        PanelBody.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 340, 90, 25));

        txtpurpose.setColumns(20);
        txtpurpose.setRows(5);
        jScrollPane1.setViewportView(txtpurpose);

        PanelBody.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 240, 60));
        PanelBody.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 380, 10));

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));

        Submit.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Add_File_27px.png"))); // NOI18N
        Submit.setText("Submit");
        Submit.setBorderPainted(false);
        Submit.setContentAreaFilled(false);
        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitMouseExited(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        PanelBody.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 430, 180, 60));
        PanelBody.add(Requestdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 240, 40));

        getContentPane().add(PanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
         int x = JOptionPane.showConfirmDialog(null,"Are You Sure You Want To Exit?","System message!",JOptionPane.YES_NO_OPTION);
    if (x==0) {    
      this.dispose();
        }
    }//GEN-LAST:event_ExitMouseClicked
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       xx = evt.getX();
       xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void SubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseEntered
     Submit.setFont(new java.awt.Font("Century Gothic Bold", 0, 14)); // NOI18N
     Submit.setForeground(Color.white);
    }//GEN-LAST:event_SubmitMouseEntered

    private void SubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseExited
    Submit.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
    Submit.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_SubmitMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i + " ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){              
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        if(jComboBox2.getSelectedItem()=="Choose here"||jComboBox2.getSelectedItem().equals("Choose here")
          ||txtSubcat.getText().isEmpty()
          ||txtRequest.getText().isEmpty()
          ||txtposition.getText().isEmpty()
          ||txtdept.getText().isEmpty()
          ||((JTextField)Requestdate.getDateEditor().getUiComponent()).getText().isEmpty()
          ||txtpurpose.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"This field cannot be empty!","ERROR!",JOptionPane.ERROR_MESSAGE);
        }else{
        
        int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){      
        try{
        String sql = "INSERT INTO Log1_AssetRequest "
            + "(ReceivedID, AssetCategory, SubCategory, RequestBy, Position, Department, RequestDate, Purpose)"
            + "VALUES(?,?,?,?,?,?,?,?)";

            pst=conn.prepareStatement(sql);  
            pst.setString(1,txtReceiveID.getText());
            String value1=jComboBox2.getSelectedItem().toString();
            pst.setString(2, value1);  
            pst.setString(3,txtSubcat.getText());
            pst.setString(4,txtRequest.getText());
            pst.setString(5,txtposition.getText());
            pst.setString(6,txtdept.getText());
            pst.setString(7, ((JTextField)Requestdate.getDateEditor().getUiComponent()).getText());
            pst.setString(8,txtpurpose.getText());          
            pst.executeUpdate();
            AssetRequest();
          getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Add Successfull! ");        
            
            
            
               Toaster toasterManager = new Toaster();
               toasterManager.showToaster("New Item Request Received From Warehouse");
               
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        }
    }//GEN-LAST:event_SubmitActionPerformed
 //=====================AutomaticID==================================================================
    public void autoID() {
     try {
         String sql = "SELECT ReceivedID FROM Log1_Assetrequest ORDER BY ReceivedID DESC";
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         if(rs.next())
         {
             String rnno = rs.getString("ReceivedID");
             int co = rnno.length();
             String txt = rnno.substring(0, 2);
             String num = rnno.substring(2, co);
             int n = Integer.parseInt(num);
             n++;
             String snum=Integer.toString(n);
             String ftxt=txt+snum;
             txtReceiveID.setText(ftxt);
         }else{
             txtReceiveID.setText("100");
         }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e);
     }
 }
//==================================================================================================    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asset_RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asset_RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asset_RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asset_RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asset_RequestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel PanelBody;
    private com.toedter.calendar.JDateChooser Requestdate;
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField txtReceiveID;
    private javax.swing.JTextField txtRequest;
    private javax.swing.JTextField txtSubcat;
    private javax.swing.JTextField txtdept;
    private javax.swing.JTextField txtposition;
    private javax.swing.JTextArea txtpurpose;
    // End of variables declaration//GEN-END:variables
}
