/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import static Module.Asset.jTable_Assets;
import Module.ServerConnection;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Jayjomjohn
 */
public class Asset_ManageAsset extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
     
    public Asset_ManageAsset() {
        this.person_image = null;
        initComponents();
       conn=ServerConnection.ConnecrDb();
     
       jTable1_Asset.setShowGrid(true);
       jTable1_Asset.setGridColor(Color.DARK_GRAY);
       jTable1_Asset.setSelectionBackground(Color.lightGray);
       
       JTableHeader th = jTable1_Asset.getTableHeader();
       th.setForeground(Color.BLACK);
       th.setFont(new Font("Century Gothic", Font.BOLD, 14));
      
       viewtable();
    }
//============================================================================================    
  public final void viewtable() { 
        DefaultTableModel model = (DefaultTableModel) jTable1_Asset.getModel(); 
        try{
            String sql ="SELECT * FROM Log1_Assetlist";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1_Asset.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
       catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());         
        }     
    } 
 //===========================================================================================
 public final void asset_table() {       
        try{         
            String sql ="SELECT * FROM Log1_Assetlist";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           Module.Asset.jTable_Assets.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
           }
       catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
    } 
 //============================================================================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BodyPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Exit = new javax.swing.JLabel();
        SIdeBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        branc = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        subcat = new javax.swing.JTextField();
        jComboBox_category = new javax.swing.JComboBox<>();
        owner = new javax.swing.JTextField();
        department = new javax.swing.JComboBox<>();
        jComboBox_branches = new javax.swing.JComboBox<>();
        sn = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        assetid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        servicelyf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox_source = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        Update = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Delete = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Clear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1_Asset = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        BodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        BodyPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        BodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Manage Asset");
        BodyPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 30));
        BodyPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1080, 10));

        Exit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        BodyPanel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 40, 30));

        SIdeBar.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout SIdeBarLayout = new javax.swing.GroupLayout(SIdeBar);
        SIdeBar.setLayout(SIdeBarLayout);
        SIdeBarLayout.setHorizontalGroup(
            SIdeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        SIdeBarLayout.setVerticalGroup(
            SIdeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        BodyPanel.add(SIdeBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 600));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Asset ID:");
        BodyPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 85, 25));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("P/N");
        BodyPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 85, 25));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("S/N");
        BodyPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 85, 25));

        branc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        branc.setText("Branches");
        BodyPanel.add(branc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 85, 25));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel15.setText("Department");
        BodyPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 85, 25));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Owner");
        BodyPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 85, 25));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Category");
        BodyPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 85, 25));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Sub-Category");
        BodyPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 85, 25));

        subcat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BodyPanel.add(subcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 157, -1));

        jComboBox_category.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here:", "Computer", "Furniture", "Stationary", "Electronics", "Others" }));
        BodyPanel.add(jComboBox_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 157, -1));

        owner.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BodyPanel.add(owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 157, -1));

        department.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here", " ", "Office of the President", "Office of the Vice President", "Faculty Department", "Admin Department", "Registrar", "Cashier", "I.T Department", " ", " " }));
        BodyPanel.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 157, -1));

        jComboBox_branches.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_branches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here", " ", "Main", "Bulacan", "MV" }));
        BodyPanel.add(jComboBox_branches, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 157, -1));

        sn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BodyPanel.add(sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 157, -1));

        pn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BodyPanel.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 157, -1));

        assetid.setEditable(false);
        assetid.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        assetid.setToolTipText("Numbers");
        assetid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                assetidKeyTyped(evt);
            }
        });
        BodyPanel.add(assetid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 157, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Cost");
        BodyPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 85, 25));

        cost.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cost.setToolTipText("Numbers");
        cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costKeyTyped(evt);
            }
        });
        BodyPanel.add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 157, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Brand");
        BodyPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 85, 25));

        brand.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BodyPanel.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 157, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Service Life");
        BodyPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 85, 25));

        servicelyf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BodyPanel.add(servicelyf, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 157, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Source");
        BodyPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 85, 25));

        jComboBox_source.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here:", " ", "Out Stock", "In Stock" }));
        BodyPanel.add(jComboBox_source, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 157, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel16.setText("Service Date");
        BodyPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 85, 25));
        BodyPanel.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 157, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Description");
        BodyPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 85, 25));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        BodyPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 260, 50));
        BodyPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 528, 1060, 10));

        jPanel4.setBackground(new java.awt.Color(30, 130, 76));
        jPanel4.setMaximumSize(new java.awt.Dimension(121, 45));
        jPanel4.setMinimumSize(new java.awt.Dimension(121, 45));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Update.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Update.setForeground(new java.awt.Color(204, 204, 204));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Edit_File_27px.png"))); // NOI18N
        Update.setText("Update");
        Update.setContentAreaFilled(false);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel4.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 140, 30));

        BodyPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 160, 40));

        jPanel5.setBackground(new java.awt.Color(150, 40, 27));

        Delete.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Delete.setForeground(new java.awt.Color(204, 204, 204));
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Delete_File_27px.png"))); // NOI18N
        Delete.setText("Delete");
        Delete.setContentAreaFilled(false);
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BodyPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 120, 40));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        Clear.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(204, 204, 204));
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Erase_25px.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.setContentAreaFilled(false);
        Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClearMouseExited(evt);
            }
        });
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        BodyPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 120, 40));

        jTable1_Asset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Asset_ID", "PN", "SN", "Branches", "Owner", "Category", "Sub_Category", "Cost", "Brandl ", "Service_Life", "Source", "Service_Date", "Description", "Pictures"
            }
        ));
        jTable1_Asset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1_Asset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_AssetMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1_Asset);

        BodyPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 260, 1070, 260));

        getContentPane().add(BodyPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
         int x = JOptionPane.showConfirmDialog(null,"Are You Sure You Want To Exit Form?","System message!",JOptionPane.YES_NO_OPTION);
    if (x==0) {    
      this.dispose();
        }
    }//GEN-LAST:event_ExitMouseClicked
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         xx = evt.getX();
         xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
    Update.setFont(new java.awt.Font("Century Gothic", 1, 16));
    Update.setForeground(Color.white);
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
    Update.setFont(new java.awt.Font("Century Gothic", 1, 12));
    Update.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_UpdateMouseExited

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
    Delete.setFont(new java.awt.Font("Century Gothic", 1, 16));
    Delete.setForeground(Color.white);
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
    Delete.setFont(new java.awt.Font("Century Gothic", 1, 12));
    Delete.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_DeleteMouseExited

    private void ClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseEntered
    Clear.setFont(new java.awt.Font("Century Gothic", 1, 16));
    Clear.setForeground(Color.white);
    }//GEN-LAST:event_ClearMouseEntered

    private void ClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseExited
    Clear.setFont(new java.awt.Font("Century Gothic", 1, 12));
    Clear.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_ClearMouseExited
String filename=null;
byte[] person_image;
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        
               if(!jTable1_Asset.getSelectionModel().isSelectionEmpty()){
        
       int x = JOptionPane.showConfirmDialog(null,"Do You Really Want To Update?","Updated",JOptionPane.YES_NO_OPTION);
       if(x==0){   
        try{
        int row =jTable1_Asset.getSelectedRow();
        String value = (jTable1_Asset.getModel().getValueAt(row, 0).toString());
        String sql ="UPDATE Log1_Assetlist SET asset_id=?, pn=?, sn=?, branches=?, department=?, owner=?, category=?,sub_category=?, cost=?, brand=?, service_life=?, source=?, service_date=?, description=? where asset_id="+value;
        pst=conn.prepareStatement(sql);
        
            pst.setString(1,assetid.getText());
            pst.setString(2,pn.getText());
            pst.setString(3,sn.getText());
            
            String value1=jComboBox_branches.getSelectedItem().toString();
            pst.setString(4, value1);  
            
            String value2=department.getSelectedItem().toString();
            pst.setString(5, value2);  
            pst.setString(6,owner.getText());
            
            String value3=jComboBox_category.getSelectedItem().toString();
            pst.setString(7, value3);  
            
            pst.setString(8,subcat.getText());
            pst.setString(9,cost.getText());
            pst.setString(10,brand.getText());
            pst.setString(11,servicelyf.getText());
      
            String value4=jComboBox_source.getSelectedItem().toString();
            pst.setString(12, value4);             
            pst.setString(13, ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            pst.setString(14,jTextArea1.getText());
           
            pst.executeUpdate();
            viewtable();
            asset_table();
           jTable_Assets.updateUI();
           
          JOptionPane.showMessageDialog(null, "Updated Successfully!");
          this.dispose();
              
        } catch (HeadlessException | SQLException e) {
              JOptionPane.showMessageDialog(null, e);
        }
        }
               }
    }//GEN-LAST:event_UpdateActionPerformed

    private void jTable1_AssetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_AssetMouseClicked
       
         DefaultTableModel model = (DefaultTableModel) jTable1_Asset.getModel(); 
   
        try{
            int row = jTable1_Asset.getSelectedRow();
            String Table_click=(jTable1_Asset.getModel().getValueAt(row,0).toString());
     
            String sql = "SELECT * FROM Log1_Assetlist where asset_id='"+Table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()) {
                
            String a1 = rs.getString("asset_id");
            assetid.setText(a1);
            String a2 = rs.getString("pn");
            pn.setText(a2);
            String a3 = rs.getString("sn");
            sn.setText(a3);
            String a4 = rs.getString("branches");
            jComboBox_branches.setSelectedItem(a4);
            String a5 = rs.getString("department");
            department.setSelectedItem(a5);
            String a6 = rs.getString("owner");
            owner.setText(a6);
            String a7 = rs.getString("category");
            jComboBox_category.setSelectedItem(a7);
            String a8 = rs.getString("sub_category");
            subcat.setText(a8);
            String a9 = rs.getString("cost");
            cost.setText(a9);
            String a10 = rs.getString("brand");
            brand.setText(a10);
            String a11 = rs.getString("service_life");
            servicelyf.setText(a11);
            String a12 = rs.getString("source");
            jComboBox_source.setSelectedItem(a12);           
            String a13=rs.getString("service_date"); 
            ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(a13);
            String a14 = rs.getString("description");
            jTextArea1.setText(a14);
           }     
        }catch(SQLException e) {
        JOptionPane.showMessageDialog(null, e);      
        } 
    }//GEN-LAST:event_jTable1_AssetMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
      if(!jTable1_Asset.getSelectionModel().isSelectionEmpty()){
           
   int p = JOptionPane.showConfirmDialog(null,"DO YOU RELLY WANT TO DELETE ?","DELETE",JOptionPane.YES_NO_OPTION);
    if(p==0){
    
        try{
            int row =jTable1_Asset.getSelectedRow();
            String value = (jTable1_Asset.getModel().getValueAt(row, 0).toString());
            String sql ="DELETE FROM Log1_Assetlist where asset_id="+value;
            pst=conn.prepareStatement(sql);
          
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable1_Asset.getModel();
            model.setRowCount(0);
            viewtable();
            asset_table();
            jTable_Assets.updateUI();
            JOptionPane.showMessageDialog(null,"Entry Successfully Deleted","Deleted", 3);
         
            }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e);   
        }        
        }
    }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
       assetid.setText("");
       pn.setText("");
       sn.setText("");
       jComboBox_branches.setSelectedIndex(0);
       department.setSelectedIndex(0);
       owner.setText("");
       jComboBox_category.setSelectedIndex(0);
       subcat.setText("");
       cost.setText("");
       brand.setText("");
       servicelyf.setText("");
       jComboBox_source.setSelectedIndex(0);
       jDateChooser1.setDate(null);
       jTextArea1.setText("");     
    }//GEN-LAST:event_ClearActionPerformed

    private void costKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costKeyTyped
      if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_costKeyTyped

    private void assetidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_assetidKeyTyped
          if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_assetidKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i +" ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){              
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asset_ManageAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asset_ManageAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asset_ManageAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asset_ManageAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asset_ManageAsset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel SIdeBar;
    private javax.swing.JButton Update;
    private javax.swing.JTextField assetid;
    private javax.swing.JLabel branc;
    private javax.swing.JTextField brand;
    private javax.swing.JTextField cost;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JComboBox<String> jComboBox_branches;
    private javax.swing.JComboBox<String> jComboBox_category;
    private javax.swing.JComboBox<String> jComboBox_source;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1_Asset;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField owner;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField servicelyf;
    private javax.swing.JTextField sn;
    private javax.swing.JTextField subcat;
    // End of variables declaration//GEN-END:variables
}
