/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import static Module.Asset.jTable2;
import static Module.Asset.jTable4;
import Module.LoginKo;
import Module.ServerConnection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jayjomjohn
 */
public class Asset_AddAsset extends javax.swing.JFrame {

    public Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
  
    
    public Asset_AddAsset() {
        initComponents();
        conn=ServerConnection.ConnecrDb();
      autoID();
        
    }
    
    
//=====================================================================================
public final void assettable4() {       
        try{         
            String sql ="SELECT * FROM Log1_Assetlist";
            pst=getConn().prepareStatement(sql);
            rs=pst.executeQuery();
            jTable4.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
           }
       catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }    
//======================================================================================    
public final void asset_table() {       
        try{         
            String sql ="SELECT * FROM Log1_Assetlist";
            pst=getConn().prepareStatement(sql);
            rs=pst.executeQuery();
           Module.Asset.jTable_Assets.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
           }
       catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
    } 
//=======================================================================================
    public void Assettbl() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel(); 
        try{       
            String sql ="SELECT * FROM Log1_Assetlist";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable2.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
             }catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
     }    finally{
                        try{
                             rs.close();
                             pst.close();
                            }catch(Exception e){            
                          }
                    }
    } 
//==================================================================================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        service_lyf = new javax.swing.JTextField();
        assetid = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_branches = new javax.swing.JComboBox<>();
        department = new javax.swing.JComboBox<>();
        sn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_category = new javax.swing.JComboBox<>();
        owner = new javax.swing.JTextField();
        subcat = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_source = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.9F);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBody.setBackground(new java.awt.Color(255, 255, 255));
        PanelBody.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        PanelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        PanelBody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 500));

        Exit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        PanelBody.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 50, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Add Asset");
        PanelBody.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 160, 30));
        PanelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 690, 10));

        service_lyf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        service_lyf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Service Life", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        service_lyf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                service_lyfKeyTyped(evt);
            }
        });
        PanelBody.add(service_lyf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 200, -1));

        assetid.setEditable(false);
        assetid.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        assetid.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asset ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        assetid.setOpaque(false);
        PanelBody.add(assetid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, -1));

        pn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        PanelBody.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Description");
        PanelBody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 80, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Branches");
        PanelBody.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 60, 30));

        jComboBox_branches.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_branches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here", " ", "Main", "Bulacan", "MV" }));
        PanelBody.add(jComboBox_branches, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 190, 30));

        department.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here", " ", "Office of the President", "Office of the Vice President", "Faculty Department", "Admin Department", "Registrar", "Cashier", "I.T Department", " ", " " }));
        PanelBody.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 190, 30));

        sn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        sn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        PanelBody.add(sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 200, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Department");
        PanelBody.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 80, 30));

        jComboBox_category.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here:", " ", "Computer", "Furniture", "Stationary", "Electronics", "Others" }));
        PanelBody.add(jComboBox_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 190, 30));

        owner.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        owner.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Owner", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        PanelBody.add(owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, -1));

        subcat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        subcat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sub Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        PanelBody.add(subcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 200, -1));

        cost.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cost.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cost", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costKeyTyped(evt);
            }
        });
        PanelBody.add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 200, -1));

        brand.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        brand.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Brand", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        PanelBody.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 200, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Category");
        PanelBody.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 80, 30));

        jComboBox_source.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here:", " ", "Out Stock", "In Stock" }));
        PanelBody.add(jComboBox_source, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 190, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Source");
        PanelBody.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 80, 30));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Service Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        PanelBody.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 200, 50));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        PanelBody.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 220, 70));
        PanelBody.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 700, 10));

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Submit.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Add_File_27px.png"))); // NOI18N
        Submit.setText("Submit");
        Submit.setContentAreaFilled(false);
        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitMouseExited(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel2.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 150, 30));

        PanelBody.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 430, 170, 50));

        getContentPane().add(PanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
       int x = JOptionPane.showConfirmDialog(null,"Are You Sure You Want To Exit?","System message!",JOptionPane.YES_NO_OPTION);
    if (x==0) {    
      this.dispose();
        }
    }//GEN-LAST:event_ExitMouseClicked
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
        
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         
         xx = evt.getX();
         xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void SubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseEntered
    Submit.setFont(new java.awt.Font("Century Gothic Bold", 1, 16));
    Submit.setForeground(Color.white);
    }//GEN-LAST:event_SubmitMouseEntered

    private void SubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseExited
    Submit .setFont(new java.awt.Font("Century Gothic", 1, 12));
    Submit.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_SubmitMouseExited

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
//validation
          if (pn.getText().isEmpty() 
          || sn.getText().isEmpty() 
          || jComboBox_branches.getSelectedItem()=="Choose here" ||jComboBox_branches.getSelectedItem().equals("Choose here")
          ||department.getSelectedItem()=="Choose here"||department.getSelectedItem().equals("Choose here")
          ||owner.getText().isEmpty()
          ||jComboBox_category.getSelectedItem()=="Choose here"|| jComboBox_category.getSelectedItem().equals("Choose here")
          ||subcat.getText().isEmpty()
          ||cost.getText().isEmpty()
          ||brand.getText().isEmpty()
          ||service_lyf.getText().isEmpty()
          ||jComboBox_source.getSelectedItem()=="Choose here:"||jComboBox_source.getSelectedItem().equals("Choose here:")
          ||((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()
          ||jTextArea2.getText().isEmpty()){
              
                  JOptionPane.showMessageDialog(null,"This field cannot be empty!","ERROR!",JOptionPane.ERROR_MESSAGE);
           }else{
//JOptionMessage           
        int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){  
        try {
            String sql = "INSERT INTO Log1_Assetlist "
            + "(asset_id,pn,sn,branches,department,owner,category,sub_category,cost,brand,service_life,source,service_date,description)"
            + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            pst=getConn().prepareStatement(sql);
            pst.setString(1,assetid.getText());
            pst.setString(2,pn.getText());
            pst.setString(3,sn.getText());
            
            String value1=jComboBox_branches.getSelectedItem().toString();
            pst.setString(4, value1);  
            
            String value2=department.getSelectedItem().toString();
            pst.setString(5, value2);  
            pst.setString(6,owner.getText());
            
            String value3=jComboBox_category.getSelectedItem().toString();
            pst.setString(7, value3);  
            
            pst.setString(8,subcat.getText());
            pst.setString(9,cost.getText());
            pst.setString(10,brand.getText());
            pst.setString(11,service_lyf.getText());
            
            String value4=jComboBox_source.getSelectedItem().toString();
            pst.setString(12, value4);  
            
            pst.setString(13, ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            pst.setString(14,jTextArea2.getText());
                             
           pst.executeUpdate();  
           DefaultTableModel model = (DefaultTableModel)Module.Asset.jTable_Assets.getModel();
           model.setRowCount(0);
           asset_table() ;
           Assettbl() ;
           assettable4();
            JOptionPane.showMessageDialog(null, "Add Successfull! ");   
            this.dispose();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        }        
    }//GEN-LAST:event_SubmitActionPerformed

    private void costKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costKeyTyped
    if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_costKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i +" ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){              
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void service_lyfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_service_lyfKeyTyped
          if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_service_lyfKeyTyped
//==================================================================================================
  public void autoID() {
     try {
         String sql = "SELECT asset_id FROM Log1_Assetlist ORDER BY asset_id DESC";
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         if(rs.next())
         {
             String rnno = rs.getString("asset_id");
             int co = rnno.length();
             String txt = rnno.substring(0, 2);
             String num = rnno.substring(2, co);
             int n = Integer.parseInt(num);
             n++;
             String snum=Integer.toString(n);
             String ftxt=txt+snum;
             assetid.setText(ftxt);
         }else{
              assetid.setText("100");
         }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e);
     }
 }
//==================================================================================================
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asset_AddAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asset_AddAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asset_AddAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asset_AddAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asset_AddAsset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel PanelBody;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField assetid;
    private javax.swing.JTextField brand;
    private javax.swing.JTextField cost;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JComboBox<String> jComboBox_branches;
    private javax.swing.JComboBox<String> jComboBox_category;
    private javax.swing.JComboBox<String> jComboBox_source;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField owner;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField service_lyf;
    private javax.swing.JTextField sn;
    private javax.swing.JTextField subcat;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the conn
     */
    public Connection getConn() {
        return conn;
    }
}
