/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import static Module.PM.tablerisk;
import Module.ServerConnection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jayjomjohn
 */
public class PM_AddRisk extends javax.swing.JFrame {

   Connection conn=null;
   ResultSet rs=null;
   PreparedStatement pst=null;
   
    public PM_AddRisk() {
        initComponents();
        conn=ServerConnection.ConnecrDb();
    }
//==================================================================================================
 public final void projectrisk() {
        try{
            String sql = "SELECT * FROM Log1_projectrisk";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tablerisk.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){        
        }
}              
//==================================================================================================    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBody = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox_impact = new javax.swing.JComboBox<>();
        jComboBox_probability = new javax.swing.JComboBox<>();
        TypeOfRisk = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        a3 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBody.setBackground(new java.awt.Color(255, 255, 255));
        PanelBody.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        PanelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        PanelBody.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 540));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setText("Project Risk");
        PanelBody.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 130, 40));

        exit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        PanelBody.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 0, 30, 30));
        PanelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 430, 10));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Type of Risks");
        PanelBody.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 130, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Probability");
        PanelBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Impact");
        PanelBody.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText(" Date");
        PanelBody.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 140, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Response");
        PanelBody.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 140, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        PanelBody.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 230, 80));
        PanelBody.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 230, 30));

        jComboBox_impact.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_impact.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High", " ", " " }));
        PanelBody.add(jComboBox_impact, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 230, 30));

        jComboBox_probability.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_probability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High", " ", " " }));
        PanelBody.add(jComboBox_probability, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 230, 30));

        TypeOfRisk.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TypeOfRisk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seasonal Risk", "Procurement Risk", "Warehouse Risk", "Financial Risk", "People", " ", " ", " " }));
        PanelBody.add(TypeOfRisk, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 230, 30));
        PanelBody.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 420, 10));

        jPanel8.setBackground(new java.awt.Color(34, 49, 63));

        Add.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Add.setForeground(new java.awt.Color(204, 204, 204));
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Add_File_27px.png"))); // NOI18N
        Add.setText("Add");
        Add.setBorder(null);
        Add.setContentAreaFilled(false);
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        PanelBody.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 150, -1));

        a3.setEditable(false);
        a3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Priority", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        a3.setOpaque(false);
        PanelBody.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 390, 50));

        a1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a1.setToolTipText("Enter Your ProjectID");
        a1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ProjectID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a1KeyReleased(evt);
            }
        });
        PanelBody.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 170, 50));

        a2.setEditable(false);
        a2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ProjectName", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        a2.setOpaque(false);
        PanelBody.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 390, 50));

        getContentPane().add(PanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        dispose();
    }//GEN-LAST:event_exitMouseClicked
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       xx = evt.getX();
       xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
      Add.setFont(new java.awt.Font("Century Gothic Bold", 1, 16));
      Add.setForeground(Color.white);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
      Add.setFont(new java.awt.Font("Century Gothic", 1, 12));
      Add.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_AddMouseExited

    private void a1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyReleased
  
       try{
          String sql = "select * from Log1_project where projectid=?";
          pst=conn.prepareCall(sql);
          pst.setString(1,a1.getText());
          rs = pst.executeQuery();
         
          if(rs.next()) { 
           a2.setText(rs.getString("ProjectName"));
           a3.setText(rs.getString("Priority"));
            }else{
              a2.setText("");
              a3.setText("");
          }       
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_a1KeyReleased

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
       int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){  
        try {
            String sql = "INSERT INTO Log1_projectrisk "
            + "(projectid, projectname, priority, typeofrisk, probability, impact, date, response)"
            + "VALUES (?,?,?,?,?,?,?,?)";

            pst=conn.prepareStatement(sql);
            pst.setString(1,a1.getText());
            pst.setString(2,a2.getText());
            pst.setString(3,a3.getText());
            pst.setString(4,TypeOfRisk.getSelectedItem().toString());
            pst.setString(5,jComboBox_probability.getSelectedItem().toString());
            pst.setString(6,jComboBox_impact.getSelectedItem().toString());
            pst.setString(7,((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText());
            pst.setString(8,jTextArea1.getText());                                         
            pst.executeUpdate();  
             projectrisk();
            JOptionPane.showMessageDialog(null, "Add Successfull! ");   
               this.dispose();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }   
        }
    }//GEN-LAST:event_AddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i + " ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){              
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_AddRisk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_AddRisk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_AddRisk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_AddRisk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_AddRisk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JPanel PanelBody;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JComboBox<String> TypeOfRisk;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JLabel exit;
    private javax.swing.JComboBox<String> jComboBox_impact;
    private javax.swing.JComboBox<String> jComboBox_probability;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
