/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import static Module.PM.jTable_ProjectList;
import Module.ServerConnection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jayjomjohn
 */
public class PM_AddNew_Project extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public PM_AddNew_Project() {
        initComponents();
        conn=ServerConnection.ConnecrDb();
        
        autoID();
    }
//==================================================================================================
public final void allproject() {
        try{
            String sql = "SELECT * FROM Log1_project ";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable_ProjectList.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){        
        }
}         
//==================================================================================================    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBody = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        projID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        projectname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_priority = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectDescrip = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBody.setBackground(new java.awt.Color(255, 255, 255));
        PanelBody.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        PanelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Add New Project");
        PanelBody.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 190, 30));

        Exit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        PanelBody.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 2, 40, 35));
        PanelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 380, 10));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Project ID");
        PanelBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, 30));

        projID.setEditable(false);
        projID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        projID.setToolTipText("Project ID");
        projID.setBorder(null);
        projID.setOpaque(false);
        projID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projIDActionPerformed(evt);
            }
        });
        PanelBody.add(projID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 200, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Project Name");
        PanelBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 30));

        projectname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        projectname.setToolTipText("Project Name");
        projectname.setBorder(null);
        PanelBody.add(projectname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 200, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Priority");
        PanelBody.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 130, 30));

        jComboBox_priority.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_priority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Choose Here-", " ", "Low", "Medium", "High", " ", " " }));
        jComboBox_priority.setToolTipText("Choose Here!");
        PanelBody.add(jComboBox_priority, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Start Date");
        PanelBody.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 130, 30));
        PanelBody.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 200, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Done");
        PanelBody.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 110, 30));
        PanelBody.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 200, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Project Description");
        PanelBody.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 120, 30));

        projectDescrip.setColumns(20);
        projectDescrip.setRows(5);
        projectDescrip.setToolTipText("Project Description");
        jScrollPane2.setViewportView(projectDescrip);

        PanelBody.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 200, 80));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel15.setText("Status");
        PanelBody.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 130, 30));

        jComboBox2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Choose Here-", " ", "On Going", "Finish" }));
        jComboBox2.setToolTipText("Choose Here!");
        PanelBody.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 200, 30));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        PanelBody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 500));
        PanelBody.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 200, 10));

        jPanel8.setBackground(new java.awt.Color(34, 49, 63));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Add.setForeground(new java.awt.Color(204, 204, 204));
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Add_File_27px.png"))); // NOI18N
        Add.setText("Add");
        Add.setBorder(null);
        Add.setContentAreaFilled(false);
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel8.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 150, -1));

        PanelBody.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 170, 50));
        PanelBody.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 200, 10));
        PanelBody.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 418, 390, 10));

        getContentPane().add(PanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        dispose();
    }//GEN-LAST:event_ExitMouseClicked
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
    Add.setFont(new java.awt.Font("Century Gothic Bold", 1, 16));
    Add.setForeground(Color.white);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
    Add.setFont(new java.awt.Font("Century Gothic", 1, 12));
    Add.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_AddMouseExited

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
       
        if(projectname.getText().isEmpty()
                ||jComboBox_priority.getSelectedItem()=="-Choose Here-" ||jComboBox_priority.getSelectedItem().equals("-Choose Here-")
                ||((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText().isEmpty()
                ||((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()
                ||projectDescrip.getText().isEmpty()
                ||jComboBox2.getSelectedItem()=="-Choose Here-" ||jComboBox2.getSelectedItem().equals("-Choose Here-")){
                        JOptionPane.showMessageDialog(null,"This field cannot be empty!","ERROR!",JOptionPane.ERROR_MESSAGE);
        }else{
        
        
        int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){  
        try {
            String sql = "INSERT INTO Log1_project "
            + "(projectid, projectname, priority, startdate, enddate, projectdescription, status)"
            + "VALUES (?,?,?,?,?,?,?)";

            pst=conn.prepareStatement(sql);
            pst.setString(1,projID.getText());
            pst.setString(2,projectname.getText());
            pst.setString(3,jComboBox_priority.getSelectedItem().toString());
            pst.setString(4,((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText());
            pst.setString(5,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            pst.setString(6,projectDescrip.getText());
            pst.setString(7,jComboBox2.getSelectedItem().toString());
            pst.execute();  
            allproject() ;
           
            
            JOptionPane.showMessageDialog(null, "Add Successfull! ");   
             this.dispose();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }   
        }
        }
    }//GEN-LAST:event_AddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                 for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i + " ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){              
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void projIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projIDActionPerformed
    
    }//GEN-LAST:event_projIDActionPerformed
//==================================================================================================
public void autoID() {
     try {
         String sql = "SELECT projectid FROM Log1_project ORDER BY projectid DESC";
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         if(rs.next())
         {
             String rnno = rs.getString("projectid");
             int co = rnno.length();
             String txt = rnno.substring(0, 2);
             String num = rnno.substring(2, co);
             int n = Integer.parseInt(num);
             n++;
             String snum=Integer.toString(n);
             String ftxt=txt+snum;
             projID.setText(ftxt);
         }else{
             projID.setText("100");
         }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e);
     }
 }        
//==================================================================================================    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_AddNew_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_AddNew_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_AddNew_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_AddNew_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_AddNew_Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel PanelBody;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox_priority;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField projID;
    private javax.swing.JTextArea projectDescrip;
    private javax.swing.JTextField projectname;
    // End of variables declaration//GEN-END:variables
}
