/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import static Module.PM.tablerisk;
import Module.ServerConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jayjomjohn
 */
public class PM_Manage_Risk extends javax.swing.JFrame {
 
   Connection conn=null;
   ResultSet rs=null;
   PreparedStatement pst=null;
   
    public PM_Manage_Risk() {
        initComponents();
        conn=ServerConnection.ConnecrDb();
          this.Option.setSelected(true);
          
          projectrisktable() ;
    }
//==================================================================================================
 public final void projectrisk() {
        try{
            String sql = "SELECT * FROM Log1_projectrisk";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tablerisk.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){        
        }
}          
//==================================================================================================
 public final void projectrisktable() {
        try{
            String sql = "SELECT * FROM Log1_projectrisk";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){        
        }
}     
//================================================================================================== 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBody = new javax.swing.JPanel();
        SideButton = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Clear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Edit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Update = new javax.swing.JButton();
        Option = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        exit = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        w7 = new javax.swing.JTextArea();
        Date = new com.toedter.calendar.JDateChooser();
        w6 = new javax.swing.JComboBox<>();
        w5 = new javax.swing.JComboBox<>();
        w4 = new javax.swing.JComboBox<>();
        w3 = new javax.swing.JTextField();
        w1 = new javax.swing.JTextField();
        w2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(940, 430));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBody.setBackground(new java.awt.Color(255, 255, 255));
        PanelBody.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        PanelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideButton.setBackground(new java.awt.Color(0, 102, 153));
        SideButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(211, 84, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Clear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Clear.setForeground(new java.awt.Color(204, 204, 204));
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Reset_27px.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.setContentAreaFilled(false);
        Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 5, 120, 40));

        SideButton.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, 50));

        jPanel2.setBackground(new java.awt.Color(103, 65, 114));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Edit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Edit.setForeground(new java.awt.Color(204, 204, 204));
        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Edit_26px.png"))); // NOI18N
        Edit.setText("EDIT");
        Edit.setContentAreaFilled(false);
        Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel2.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 5, 120, 40));

        SideButton.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 50));

        jPanel4.setBackground(new java.awt.Color(30, 130, 76));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Update.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(204, 204, 204));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Edit_File_27px.png"))); // NOI18N
        Update.setText("Update");
        Update.setContentAreaFilled(false);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel4.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 5, 130, 40));

        SideButton.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 50));

        PanelBody.add(SideButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 30, 200, 400));

        Option.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Option.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Multiple_Choice_25px.png"))); // NOI18N
        Option.setText("Option");
        Option.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        Option.setContentAreaFilled(false);
        Option.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Option.setFocusPainted(false);
        Option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionActionPerformed(evt);
            }
        });
        PanelBody.add(Option, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        PanelBody.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 470, 350));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Manage");
        PanelBody.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 240, 40));
        PanelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 700, 10));

        exit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        PanelBody.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 0, 30, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Type of Risks");
        PanelBody.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Probability");
        PanelBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Impact");
        PanelBody.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText(" Date");
        PanelBody.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 140, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Response");
        PanelBody.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 140, 30));

        w7.setColumns(20);
        w7.setRows(5);
        jScrollPane2.setViewportView(w7);

        PanelBody.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 230, 80));
        PanelBody.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 230, 30));

        w6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        w6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High", " ", " " }));
        PanelBody.add(w6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 230, 30));

        w5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        w5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High", " ", " " }));
        PanelBody.add(w5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 230, 30));

        w4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        w4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seasonal Risk", "Procurement Risk", "Warehouse Risk", "Equipment Risk", "Financial Risk", "Safetyl Risk", " ", " ", " " }));
        PanelBody.add(w4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 230, 30));

        w3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        w3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Priority", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        PanelBody.add(w3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 390, 50));

        w1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        w1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ProjectID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        PanelBody.add(w1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, 50));

        w2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        w2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ProjectID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        PanelBody.add(w2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 230, 50));

        getContentPane().add(PanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       xx = evt.getX();
       xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void OptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionActionPerformed
      int position = this.SideButton.getX();
        if( position > -1)
        {
          Animacion.Animacion.mover_izquierda(0, -190, 2, 2, SideButton);   
        }else{
          Animacion.Animacion.mover_derecha(-190, 0, 2, 2, SideButton);
        }       
    }//GEN-LAST:event_OptionActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //disable Button
      
        Update.setEnabled(false);
       
        Clear.setEnabled(false);
        //Disable Combo
        w4.setEnabled(false);
        w5.setEnabled(false);
        w6.setEnabled(false);
        Date.setEnabled(false);
        w7.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        //disable Button
        Edit.setEnabled(false);
    
        Update.setEnabled(true);
      
        Clear.setEnabled(true);
        //Disable Combo
        w4.setEnabled(true);
        w5.setEnabled(true);
        w6.setEnabled(true);
        Date.setEnabled(true);
        w7.setEnabled(true);
    }//GEN-LAST:event_EditActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
       int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Update Record?","Update",JOptionPane.YES_NO_OPTION);     
  if(x==0){
        if(!jTable1.getSelectionModel().isSelectionEmpty()){
      try { 
       int row =jTable1.getSelectedRow();
        String value = (jTable1.getModel().getValueAt(row, 0).toString());
        String sql ="UPDATE Log1_projectrisk SET projectid=?, "
                + "projectname=?, "
                + "priority=?,"
                + "typeofrisk=?,"
                + "probability=?,"
                + "impact=?,"
                + "date=?,"
                + "response=? where projectid="+value;
          pst=conn.prepareStatement(sql);  
          
            pst.setString(1,w1.getText());
            pst.setString(2,w2.getText());
            pst.setString(3,w3.getText());
            pst.setString(4,w4.getSelectedItem().toString());
            pst.setString(5,w5.getSelectedItem().toString());
            pst.setString(6,w6.getSelectedItem().toString());
            pst.setString(7,((JTextField)Date.getDateEditor().getUiComponent()).getText());
            pst.setString(8,w7.getText());     
            
            pst.executeUpdate(); 
            projectrisktable() ;
             projectrisk();
             
            JOptionPane.showMessageDialog(null, "Updated Successfull!");
            this.dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
  }
        
    }//GEN-LAST:event_UpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       try{
            int row = jTable1.getSelectedRow();
            String Table_click=(jTable1.getModel().getValueAt(row, 0).toString());
            String sql = "select * from Log1_projectrisk where projectid='"+Table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()) {
              w1.setText(rs.getString("projectid"));
              w2.setText(rs.getString("projectname"));
              w3.setText(rs.getString("Priority"));
              w4.setSelectedItem(rs.getString("typeofrisk"));
              w5.setSelectedItem(rs.getString("probability"));
              w6.setSelectedItem(rs.getString("Impact"));
              ((JTextField)Date.getDateEditor().getUiComponent()).setText(rs.getString("Date"));
              w7.setText(rs.getString("response"));
          }           
        }catch(Exception e) {          
            JOptionPane.showMessageDialog(null, e);
        }
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
              for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i + " ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){              
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
       
      w1.setText("");
      w2.setText("");
      w3.setText("");
      w4.setSelectedIndex(0);
      w5.setSelectedIndex(0);
      w6.setSelectedIndex(0);
       ((JTextField)Date.getDateEditor().getUiComponent()).setText("");
       w7.setText("");
        
                        
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_Manage_Risk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_Manage_Risk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_Manage_Risk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_Manage_Risk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_Manage_Risk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Option;
    private javax.swing.JPanel PanelBody;
    private javax.swing.JPanel SideButton;
    private javax.swing.JButton Update;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static final javax.swing.JTable jTable1 = new javax.swing.JTable();
    private javax.swing.JTextField w1;
    private javax.swing.JTextField w2;
    private javax.swing.JTextField w3;
    private javax.swing.JComboBox<String> w4;
    private javax.swing.JComboBox<String> w5;
    private javax.swing.JComboBox<String> w6;
    private javax.swing.JTextArea w7;
    // End of variables declaration//GEN-END:variables
}
