/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import Module.ServerConnection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jayjomjohn
 */
public class Procure_BiddingResultDetails extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Procure_BiddingResultDetails() {
        initComponents();
        conn=ServerConnection.ConnecrDb();
        
    
//        autoID();
    }

//===============================================================================================
   
//public void Biddingtable() {
//     try{
//            String sql ="SELECT * FROM procure_BiddingResult";
//            pst=conn.prepareStatement(sql);
//            rs=pst.executeQuery();
//            tableBidding.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
//             }
//       catch(SQLException e) {
//          JOptionPane.showMessageDialog(this, e.getMessage());
//        }
//    }  
////=============================================================================================== 
//  public void AwardList() {
//     try{
//            String sql ="SELECT * FROM Log1_procure_AwardingList";
//            pst=conn.prepareStatement(sql);
//            rs=pst.executeQuery();
//            Module.Procurement.jTable_Award.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
//             }
//       catch(SQLException ex) {
//           Logger.getLogger(Procure_BiddingResultDetails.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }  
//=============================================================================================== 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBidding = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        BidderID = new javax.swing.JTextField();
        BidderName = new javax.swing.JTextField();
        CN = new javax.swing.JTextField();
        ItemName = new javax.swing.JTextField();
        Qty = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtAwardID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBody.setBackground(new java.awt.Color(255, 255, 255));
        PanelBody.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        PanelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        PanelBody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 540));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Bidding Result Details");
        PanelBody.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 190, 30));
        PanelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 820, 10));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        PanelBody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 40, 30));

        tableBidding.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tableBidding.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableBidding.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableBidding.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBiddingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBidding);

        PanelBody.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 820, 180));

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Winner_30px.png"))); // NOI18N
        jButton1.setText("Add Awarding List");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        PanelBody.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 230, 50));

        price.setEditable(false);
        price.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        price.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        price.setOpaque(false);
        PanelBody.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 190, 50));

        BidderID.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BidderID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bidder ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        BidderID.setOpaque(false);
        BidderID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BidderIDKeyReleased(evt);
            }
        });
        PanelBody.add(BidderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, 50));

        BidderName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BidderName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bidder Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        BidderName.setOpaque(false);
        PanelBody.add(BidderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, 50));

        CN.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        CN.setOpaque(false);
        PanelBody.add(CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 190, 50));

        ItemName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ItemName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        ItemName.setOpaque(false);
        PanelBody.add(ItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 190, 50));

        Qty.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Qty.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        Qty.setOpaque(false);
        PanelBody.add(Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 190, 50));

        Description.setColumns(20);
        Description.setRows(5);
        Description.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jScrollPane2.setViewportView(Description);

        PanelBody.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 390, 110));
        PanelBody.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 820, 20));
        PanelBody.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 820, 10));

        txtAwardID.setEditable(false);
        txtAwardID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAwardID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AwardingID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        txtAwardID.setOpaque(false);
        PanelBody.add(txtAwardID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 200, 50));

        jPanel3.setBackground(new java.awt.Color(34, 49, 63));

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("List Supplier Table");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBody.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 180, 50));

        getContentPane().add(PanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
          xx = evt.getX();
          xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
    jButton1.setFont(new java.awt.Font("Century Gothic Bold", 1, 16));
    jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
     jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14));
     jButton1.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jButton1MouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i + " ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){              
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void tableBiddingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBiddingMouseClicked
//         DefaultTableModel model = (DefaultTableModel) tableBidding.getModel(); 
//      if(!tableBidding.getSelectionModel().isSelectionEmpty()){
//        try{
//            int row = tableBidding.getSelectedRow();
//            String Table_click=(tableBidding.getModel().getValueAt(row,0).toString());
//     
//            String sql = "SELECT * FROM Log1_procure_BiddingResult WHERE BidID='"+Table_click+"' ";  
//            pst=conn.prepareStatement(sql);
//            rs=pst.executeQuery();
//            if(rs.next()) {
//                  BidderID.setText(rs.getString("BidID"));
//                  BidderName.setText(rs.getString("Bidder_Name"));
//                  CN.setText(rs.getString("ContactNo"));
//                  ItemName.setText(rs.getString("ItemName"));
//                  Qty.setText(rs.getString("Quantity"));
//                  price.setText(rs.getString("Price"));
//                  Description.setText(rs.getString("Description"));
//           }  
//        }catch(SQLException e) {
//        JOptionPane.showMessageDialog(null, e);      
//        } 
//        }
    }//GEN-LAST:event_tableBiddingMouseClicked

    private void BidderIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BidderIDKeyReleased
//         
//          try{
//            String sql = "SELECT * FROM Log1_procure_BiddingResult WHERE BidID= ? ";  
//            
//          pst=conn.prepareCall(sql);
//             pst.setString(1,BidderID.getText());
//          rs=pst.executeQuery();
//          if(rs.next()) {
//                  BidderID.setText(rs.getString("BidID"));
//                  BidderName.setText(rs.getString("Bidder_Name"));
//                  CN.setText(rs.getString("ContactNo"));
//                  ItemName.setText(rs.getString("ItemName"));
//                  Qty.setText(rs.getString("Quantity"));
//                  price.setText(rs.getString("Price"));
//                  Description.setText(rs.getString("Description"));
//           }else{                    
//                         BidderName.setText("");
//                         CN.setText("");
//                         ItemName.setText("");
//                         Qty.setText("");
//                         price.setText("");
//                         Description.setText("");
//                    }   
//          }catch(SQLException e) {
//        JOptionPane.showMessageDialog(null, e);      
//        } 
//        
    }//GEN-LAST:event_BidderIDKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//              int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","Add Record",JOptionPane.YES_NO_OPTION);
//        if(x==0){  
//        try {
//            String sql = "INSERT INTO Log1_procure_AwardingList "
//            + "(AwardNo, BidderID, BidderName, ContactNo, ItemName, Quantity, Price, Description)"
//            + "values(?,?,?,?,?,?,?,?)";
//
//            pst=conn.prepareStatement(sql);
//            pst.setString(1,txtAwardID.getText());
//            pst.setString(2, BidderID.getText());
//            pst.setString(3, BidderName.getText());
//            pst.setString(4, CN.getText());
//            pst.setString(5, ItemName.getText());
//            pst.setString(6, Qty.getText());
//            pst.setString(7, price.getText());
//            pst.setString(8, Description.getText());
//            pst.executeUpdate();
//          AwardList();
//            clear();
//        
//            
//            JOptionPane.showMessageDialog(null, "Add Successfull! ");   
//        } catch (HeadlessException | SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
//        }          
//        }
    }//GEN-LAST:event_jButton1ActionPerformed
//
//    public void autoID() {
//     try {
//         String sql = "SELECT AwardNo FROM Log1_procure_AwardingList ORDER BY AwardNo DESC";
//         pst=conn.prepareStatement(sql);
//         rs=pst.executeQuery();
//         if(rs.next())
//         {
//             String rnno = rs.getString("AwardNo");
//             int co = rnno.length();
//             String txt = rnno.substring(0, 2);
//             String num = rnno.substring(2, co);
//             int n = Integer.parseInt(num);
//             n++;
//             String snum=Integer.toString(n);
//             String ftxt=txt+snum;
//             txtAwardID.setText(ftxt);
//         }else{
//              txtAwardID.setText("100");
//         }
//     } catch (NumberFormatException | SQLException e) {
//         JOptionPane.showMessageDialog(null, e);
//     }
// }
 //==========================================================================
 
public void clear() {
          BidderName.setText("");
          CN.setText("");
          ItemName.setText("");
          Qty.setText("");
          price.setText("");
          Description.setText("");
 }     
     
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Procure_BiddingResultDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Procure_BiddingResultDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Procure_BiddingResultDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Procure_BiddingResultDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Procure_BiddingResultDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BidderID;
    private javax.swing.JTextField BidderName;
    private javax.swing.JTextField CN;
    private javax.swing.JTextArea Description;
    private javax.swing.JTextField ItemName;
    private javax.swing.JPanel PanelBody;
    private javax.swing.JTextField Qty;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField price;
    private javax.swing.JTable tableBidding;
    private javax.swing.JTextField txtAwardID;
    // End of variables declaration//GEN-END:variables
}
