/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import Module.Procurement;
import static Module.Procurement.jTable_ListofSupplier;
import Module.ServerConnection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Jayjomjohn
 */
public class Procure_UpdateRequestQS extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
   
    public Procure_UpdateRequestQS() {
        initComponents();
        conn=ServerConnection.ConnecrDb();
     
    }

//=======================================================================================
   public final void procuretable() {              
          try{         
          String sql ="SELECT * FROM Log1_procure_listofsupplier";
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          jTable_ListofSupplier.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
          }
       catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }        
    } 
//=====================================================================================    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        FindSuppID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        BN = new javax.swing.JTextField();
        CN = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        quan = new javax.swing.JTextField();
        jComboBox_TOP = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_AN = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox_Status = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_PC = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_AD = new javax.swing.JComboBox<>();
        date = new javax.swing.JTextField();
        dept = new javax.swing.JTextField();
        branch = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        itemdescrip = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        Update = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(680, 470));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 540));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Update Request Quotation Supplier");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 320, 30));

        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 30, 30));

        FindSuppID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FindSuppID.setToolTipText("Enter Your ID");
        FindSuppID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supplier ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        FindSuppID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FindSuppIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FindSuppIDKeyTyped(evt);
            }
        });
        jPanel1.add(FindSuppID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 620, 10));

        BN.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bidder Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel1.add(BN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 170, 50));

        CN.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        CN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel1.add(CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 170, 50));

        price.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        price.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 170, 50));

        quan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        quan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel1.add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 170, 40));

        jComboBox_TOP.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jComboBox_TOP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-", " ", "SO011", "SO012", "SO013", "SO014" }));
        jPanel1.add(jComboBox_TOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 150, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Type of Product");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 150, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Account Number");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 110, 30));

        jComboBox_AN.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jComboBox_AN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-", " ", "AC 0021", "AC 0022", "AC 0023", "AC 0024" }));
        jPanel1.add(jComboBox_AN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 150, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Status");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 120, 20));

        jComboBox_Status.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jComboBox_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-", " ", "Finding of Supplier", "For Approval Budget" }));
        jPanel1.add(jComboBox_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 150, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Product Category");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 150, 30));

        jComboBox_PC.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jComboBox_PC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-", " ", "IT Hardware & Software Supply", "Hardware Supply", "School in Supply" }));
        jPanel1.add(jComboBox_PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 150, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Account Description");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 150, 30));

        jComboBox_AD.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jComboBox_AD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT-", " ", "Computer Equipment", "School Supplies", "Construction Equipment", "Electrical Equipment" }));
        jPanel1.add(jComboBox_AD, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 150, 30));

        date.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        date.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 170, 40));

        dept.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        dept.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel1.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 170, 40));

        branch.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        branch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Branches", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel1.add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 170, 40));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("iTem Description");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 100, 20));

        itemdescrip.setColumns(20);
        itemdescrip.setRows(5);
        jScrollPane4.setViewportView(itemdescrip);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 200, 80));

        jPanel10.setBackground(new java.awt.Color(34, 49, 63));

        Update.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Update.setForeground(new java.awt.Color(204, 204, 204));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Edit_File_27px.png"))); // NOI18N
        Update.setText("Update");
        Update.setContentAreaFilled(false);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Update)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 130, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 382, 610, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
    Update.setFont(new java.awt.Font("Century Gothic Bold", 1, 14));
    Update.setForeground(Color.white);
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
    Update.setFont(new java.awt.Font("Century Gothic", 1, 12));
    Update.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_UpdateMouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
       this.dispose();
    }//GEN-LAST:event_ExitMouseClicked
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
           int x = evt.getXOnScreen();
           int y = evt.getYOnScreen();
           this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
          xx = evt.getX();
          xy = evt.getY();
    }//GEN-LAST:event_formMouseReleased

    private void FindSuppIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FindSuppIDKeyTyped
           if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_FindSuppIDKeyTyped

    private void FindSuppIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FindSuppIDKeyReleased
        try{
          String sql = "SELECT * FROM Log1_procure_listofsupplier where Supplier_id=?";
          pst=conn.prepareCall(sql);
          pst.setString(1,FindSuppID.getText());
          rs = pst.executeQuery();
          
          while(rs.next()) { 
          FindSuppID.setText(rs.getString("Supplier_ID"));
          BN.setText(rs.getString("Bidder_Name"));
          CN.setText(rs.getString("Contact_No"));
          price.setText(rs.getString("price"));
          
          String s1 = rs.getString("Type_of_Product");
          jComboBox_TOP.setSelectedItem(s1);
          String s2 = rs.getString("Account_Num");
          jComboBox_AN.setSelectedItem(s2);
          String s3 = rs.getString("Status");
          jComboBox_Status.setSelectedItem(s3);
          String s4 = rs.getString("Product_category");
          jComboBox_PC.setSelectedItem(s4);
           String s5 = rs.getString("Account_Description");
          jComboBox_AD.setSelectedItem(s5);
          
          date.setText(rs.getString("Date"));
          dept.setText(rs.getString("Department"));
          branch.setText(rs.getString("Branches"));
          quan.setText(rs.getString("Quantity"));
          itemdescrip.setText(rs.getString("item_description"));
            }  
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_FindSuppIDKeyReleased

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
               
        
       int x = JOptionPane.showConfirmDialog(null,"Are you sure you want to update?","System message!",JOptionPane.OK_OPTION); 
            
            if (x == 0) {  
        try{
            
      String value = FindSuppID.getText();
        String sql ="UPDATE Log1_procure_listofsupplier SET supplier_id=?, bidder_name=?, contact_no=?, price=?, "
                + "type_of_product=?, account_num=?, status=?,"
                + "product_category=?, account_description=?, "
                + "date=?, department=?, branches=?, quantity=?, item_description=? where supplier_id="+value;
          pst=conn.prepareStatement(sql);          
              pst.setString(1,FindSuppID.getText());
            pst.setString(2,BN.getText());
            pst.setString(3,CN.getText());
            pst.setString(4,price.getText());
            String value1=jComboBox_TOP.getSelectedItem().toString();
            pst.setString(5, value1);  
            String value2=jComboBox_AN.getSelectedItem().toString();
            pst.setString(6, value2);  
            String value3=jComboBox_Status.getSelectedItem().toString();
            pst.setString(7, value3);     
            String value4=jComboBox_PC.getSelectedItem().toString();
            pst.setString(8, value4);  
            String value5=jComboBox_AD.getSelectedItem().toString();
            pst.setString(9, value5); 
              pst.setString(10,date.getText());
                pst.setString(11,dept.getText());
                  pst.setString(12,branch.getText());
                    pst.setString(13,quan.getText());
                      pst.setString(14,itemdescrip.getText());
         
           
            pst.executeUpdate();      
               DefaultTableModel model = (DefaultTableModel) Procurement.jTable_ListofSupplier.getModel(); 
                 model.setRowCount(0);
           procuretable() ;
          
           
            JOptionPane.showMessageDialog(null, "Updated Successfully!");
                this.dispose();
              
        } catch (HeadlessException | SQLException e) {
              JOptionPane.showMessageDialog(null, e);
        }       
        }
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Procure_UpdateRequestQS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Procure_UpdateRequestQS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Procure_UpdateRequestQS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Procure_UpdateRequestQS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Procure_UpdateRequestQS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BN;
    private javax.swing.JTextField CN;
    private javax.swing.JLabel Exit;
    private javax.swing.JTextField FindSuppID;
    private javax.swing.JButton Update;
    private javax.swing.JTextField branch;
    private javax.swing.JTextField date;
    private javax.swing.JTextField dept;
    private javax.swing.JTextArea itemdescrip;
    private javax.swing.JComboBox<String> jComboBox_AD;
    private javax.swing.JComboBox<String> jComboBox_AN;
    private javax.swing.JComboBox<String> jComboBox_PC;
    private javax.swing.JComboBox<String> jComboBox_Status;
    private javax.swing.JComboBox<String> jComboBox_TOP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quan;
    // End of variables declaration//GEN-END:variables

}
