/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import Module.ServerConnection;
import Module.Warehouse;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jayjomjohn
 */
public class Ware_Add_Stock extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Ware_Add_Stock() {
        initComponents();
      conn=ServerConnection.ConnecrDb();
        autoID();
      
    }
//=====================================================================================
    public void waretable() {
            DefaultTableModel model = (DefaultTableModel) Warehouse.jTable_stocklistinfo.getModel(); 
        try{
            String sql ="SELECT * FROM Log1_ware_addstock";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Warehouse.jTable_stocklistinfo.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
             }catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
    } 
//=====================================================================================    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelbody = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jComboBox_branches = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_category = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        subcat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        service_life = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox_Source = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        stockID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panelbody.setBackground(new java.awt.Color(255, 255, 255));
        Panelbody.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        Panelbody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Panelbody.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 450));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        Panelbody.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 50, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Add Stock");
        Panelbody.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, 30));
        Panelbody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 670, 10));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel18.setText("Branches");
        Panelbody.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 85, 25));

        jComboBox_branches.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_branches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here", " ", "Main", "Bulacan", "MV" }));
        Panelbody.add(jComboBox_branches, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 190, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Category");
        Panelbody.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 85, 25));

        jComboBox_category.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here", "Computer", "Furniture", "Stationary", "Electronics", "Others" }));
        Panelbody.add(jComboBox_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 190, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Sub-Category");
        Panelbody.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 85, 25));

        subcat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Panelbody.add(subcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 190, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Stock");
        Panelbody.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, 25));

        cost.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cost.setToolTipText("Numbers only");
        cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costKeyTyped(evt);
            }
        });
        Panelbody.add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 190, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Brand");
        Panelbody.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 80, 30));

        brand.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Panelbody.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Service Life");
        Panelbody.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 80, 25));

        service_life.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Panelbody.add(service_life, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 190, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Source");
        Panelbody.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 85, 25));

        jComboBox_Source.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox_Source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here", "Purchase", "Return" }));
        Panelbody.add(jComboBox_Source, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 190, 30));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel16.setText("Service Date");
        Panelbody.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 85, 25));
        Panelbody.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 190, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Description");
        Panelbody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 85, 25));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Panelbody.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 190, 40));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Purposed");
        Panelbody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 85, 25));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        Panelbody.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 190, 40));

        jPanel1.setBackground(new java.awt.Color(34, 49, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add.setBackground(new java.awt.Color(31, 58, 147));
        Add.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Add.setForeground(new java.awt.Color(204, 204, 204));
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Add_File_27px.png"))); // NOI18N
        Add.setText("Add");
        Add.setBorderPainted(false);
        Add.setContentAreaFilled(false);
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 140, 30));

        Panelbody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 160, 50));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel15.setText("Cost");
        Panelbody.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 70, 25));
        Panelbody.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 190, 30));
        Panelbody.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 660, 20));

        stockID.setEditable(false);
        stockID.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        stockID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stock_ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N
        stockID.setOpaque(false);
        Panelbody.add(stockID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 290, 50));

        getContentPane().add(Panelbody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
      xx = evt.getX();
      xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void costKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costKeyTyped
            if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_costKeyTyped

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
      Add.setFont(new java.awt.Font("Century Gothic Bold", 1, 16));
      Add.setForeground(Color.white);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
      Add.setFont(new java.awt.Font("Century Gothic", 1, 12));
      Add.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_AddMouseExited

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        
        if(jComboBox_branches.getSelectedItem()=="Choose here" ||jComboBox_branches.getSelectedItem().equals("Choose here")
                ||jComboBox_category.getSelectedItem()=="Choose here" || jComboBox_category.getSelectedItem().equals("Choose here")
                ||jComboBox_Source.getSelectedItem()=="Choose here" || jComboBox_Source.getSelectedItem().equals("Chooser here")
                ||((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()
                ||subcat.getText().isEmpty()
                ||cost.getText().isEmpty()
                ||brand.getText().isEmpty()
                ||service_life.getText().isEmpty()
                ||stock.getText().isEmpty()
                ||jTextArea1.getText().isEmpty()
                ||jTextArea2.getText().isEmpty()){
               JOptionPane.showMessageDialog(null,"This field cannot be empty!","ERROR!",JOptionPane.ERROR_MESSAGE);
        }else{
               
    int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){      
        try{
        String sql = "insert into Log1_ware_addstock "
            + "(Stock_ID, Branches, Category, Sub_category, Cost, Brand, Service_Life, Source, Service_Date, Stock, Description, Purposed)"
            + "values(?,?,?,?,?,?,?,?,?,?,?,?)";

            pst=conn.prepareStatement(sql);  
            pst.setString(1,stockID.getText());
            String value1=jComboBox_branches.getSelectedItem().toString();
            pst.setString(2, value1);  
            
            String value2=jComboBox_category.getSelectedItem().toString();
            pst.setString(3, value2);             
            pst.setString(4,subcat.getText());
            pst.setString(5,cost.getText());
            pst.setString(6,brand.getText());
            pst.setString(7,service_life.getText());
            
            String value3=jComboBox_Source.getSelectedItem().toString();
            pst.setString(8, value3);
            pst.setString(9, ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());          
            pst.setString(10,stock.getText());
            pst.setString(11,jTextArea1.getText());
            pst.setString(12,jTextArea2.getText());                     
            pst.executeUpdate();
            waretable();
        
            
            JOptionPane.showMessageDialog(null, "Add Successfull! ");     
            this.dispose();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        }
    }//GEN-LAST:event_AddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i +" ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){              
            }
        }
    }//GEN-LAST:event_formWindowOpened
//==================================================================================================
 public void autoID() {
     try {
         String sql = "SELECT Stock_ID FROM Log1_ware_addstock ORDER BY Stock_ID DESC";
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         if(rs.next())
         {
             String rnno = rs.getString("Stock_ID");
             int co = rnno.length();
             String txt = rnno.substring(0, 2);
             String num = rnno.substring(2, co);
             int n = Integer.parseInt(num);
             n++;
             String snum=Integer.toString(n);
             String ftxt=txt+snum;
             stockID.setText(ftxt);
         }else{
              stockID.setText("100");
         }
     } catch (NumberFormatException | SQLException e) {
         JOptionPane.showMessageDialog(rootPane, e);
     }
 }    
//==================================================================================================
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ware_Add_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ware_Add_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ware_Add_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ware_Add_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ware_Add_Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JPanel Panelbody;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JTextField brand;
    private javax.swing.JTextField cost;
    private javax.swing.JComboBox<String> jComboBox_Source;
    private javax.swing.JComboBox<String> jComboBox_branches;
    private javax.swing.JComboBox<String> jComboBox_category;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField service_life;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField stockID;
    private javax.swing.JTextField subcat;
    // End of variables declaration//GEN-END:variables
}
