/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import static Module.Asset.jTable3;
import Module.ServerConnection;
import com.nitido.utils.toaster.Toaster;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jayjomjohn
 */
public class Ware_SendRequestFormAsset extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Ware_SendRequestFormAsset() {
        initComponents();
        conn=ServerConnection.ConnecrDb();
    }
//==================================================================================================
   public void assetrequests() {
        DefaultTableModel model = (DefaultTableModel) Module.Asset.jTable3.getModel(); 
        try{
            String sql ="SELECT * FROM Log1_AssetRequests";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           jTable3.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

             }catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
  }               
//==================================================================================================    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        a7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        a8 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SendAsset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 540));

        a7.setEditable(false);
        a7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Request Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        a7.setOpaque(false);
        jPanel1.add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 310, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 0, 40, 40));

        a1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a1.setToolTipText("Find Your ReceivedID");
        a1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ReceivedID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a1KeyReleased(evt);
            }
        });
        jPanel1.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 310, 50));

        a2.setEditable(false);
        a2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asset Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        a2.setOpaque(false);
        jPanel1.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 310, 50));

        a3.setEditable(false);
        a3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sub Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        a3.setOpaque(false);
        jPanel1.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 310, 50));

        a4.setEditable(false);
        a4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Request By", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        a4.setOpaque(false);
        jPanel1.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 310, 50));

        a5.setEditable(false);
        a5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Position", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        a5.setOpaque(false);
        jPanel1.add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 310, 50));

        a6.setEditable(false);
        a6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        a6.setOpaque(false);
        jPanel1.add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 310, 50));

        a8.setEditable(false);
        a8.setColumns(20);
        a8.setRows(5);
        a8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purposed", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        a8.setOpaque(false);
        jScrollPane1.setViewportView(a8);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 396, 310, 50));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Ware_RequestFormAsset");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 4, 270, 30));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SendAsset.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SendAsset.setForeground(new java.awt.Color(204, 204, 204));
        SendAsset.setText("Send To Asset");
        SendAsset.setContentAreaFilled(false);
        SendAsset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SendAsset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SendAssetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SendAssetMouseExited(evt);
            }
        });
        SendAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendAssetActionPerformed(evt);
            }
        });
        jPanel3.add(SendAsset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 200, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SendAssetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendAssetMouseEntered
           SendAsset.setFont(new java.awt.Font("Century Gothic Bold", 0, 18)); // NOI18N
           SendAsset.setForeground(Color.white);
    }//GEN-LAST:event_SendAssetMouseEntered

    private void SendAssetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendAssetMouseExited
          SendAsset.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
          SendAsset.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_SendAssetMouseExited

    private void SendAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendAssetActionPerformed

        if(a1.getText().isEmpty()
                ||a2.getText().isEmpty()
                ||a3.getText().isEmpty()
                ||a4.getText().isEmpty()
                ||a5.getText().isEmpty()
                ||a6.getText().isEmpty()
                ||a7.getText().isEmpty()
                ||a8.getText().isEmpty()){
                   JOptionPane.showMessageDialog(null,"This field cannot be empty!","ERROR!",JOptionPane.ERROR_MESSAGE);
        }else{
      
        int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){  
        try {
            String sql = "INSERT INTO Log1_AssetRequests "
            + "(ID, AssetCategory, SubCategory, RequestBy, Position, Department, RequestDate, Purposed)"
            + "VALUES (?,?,?,?,?,?,?,?)";

            pst=conn.prepareStatement(sql);
            pst.setString(1,a1.getText());
            pst.setString(2,a2.getText());
            pst.setString(3,a3.getText());
            pst.setString(4,a4.getText());
            pst.setString(5,a5.getText());
            pst.setString(6,a6.getText());
            pst.setString(7,a7.getText());
            pst.setString(8,a8.getText());
            pst.executeUpdate();  
            assetrequests();
                     
            JOptionPane.showMessageDialog(null, "Add Successfull! ");   
            this.dispose();
            
               Toaster toasterManager = new Toaster();
               toasterManager.showToaster("New Item Delivered Item To Asset ");
               
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }   
        }
        }
    }//GEN-LAST:event_SendAssetActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i + " ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){              
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void a1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyReleased
           try{
          String sql = "select * from Log1_Assetrequest where ReceivedID=?";
          pst=conn.prepareCall(sql);
          pst.setString(1,a1.getText());
          rs = pst.executeQuery();
           
          if(rs.next()) { 
           a2.setText(rs.getString("AssetCategory"));
           a3.setText(rs.getString("SubCategory"));
           a4.setText(rs.getString("RequestBy"));
           a5.setText(rs.getString("Position"));
           a6.setText(rs.getString("Department"));
           a7.setText(rs.getString("RequestDate"));     
           a8.setText(rs.getString("Purpose"));
    }else{
           a2.setText("");
           a3.setText("");
           a4.setText("");
           a5.setText("");
           a6.setText("");
           a7.setText("");     
           a8.setText("");
          }            
        }
          
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }   
    }//GEN-LAST:event_a1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ware_SendRequestFormAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ware_SendRequestFormAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ware_SendRequestFormAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ware_SendRequestFormAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ware_SendRequestFormAsset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendAsset;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextArea a8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
