/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import static Module.Procurement.jTable_PODetail;
import Module.ServerConnection;
import static Module.Warehouse.jTable4;
import com.nitido.utils.toaster.Toaster;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jayjomjohn
 */
public class Ware_RequestForm extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Ware_RequestForm() {
        initComponents();
        conn=ServerConnection.ConnecrDb();
        autoID() ;
        
    }
//====================================================================================== 
  public void purchaseOrder() {
        DefaultTableModel model = (DefaultTableModel) jTable_PODetail.getModel(); 
        try{
            String sql ="SELECT * FROM Log1_procure_purchaseorder";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable_PODetail.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
             }
       catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
  }             
//======================================================================================   
  public void purchaseWare() {
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel(); 
        try{
            String sql ="SELECT * FROM Log1_procure_purchaseorder";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable4.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
             }
       catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
  }   
//=======================================================================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SignReceived = new javax.swing.JTextField();
        txtRequestID = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        txtitem = new javax.swing.JTextField();
        txtRequestedby = new javax.swing.JTextField();
        txtReleasedby = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1_Depart = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2_Branches = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3_Approvedby = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(512, 525));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(512, 525));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 530));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Request Form To Purchase Order");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 300, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 52, 460, 10));

        SignReceived.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        SignReceived.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign Received", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        jPanel1.add(SignReceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 220, 50));

        txtRequestID.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtRequestID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RequestID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        txtRequestID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRequestIDKeyReleased(evt);
            }
        });
        jPanel1.add(txtRequestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 180, 50));

        txtQty.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtQty.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quantity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 180, 40));

        txtitem.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtitem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        jPanel1.add(txtitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 180, 40));

        txtRequestedby.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtRequestedby.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Requested By", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        jPanel1.add(txtRequestedby, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 220, 40));

        txtReleasedby.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtReleasedby.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Released By", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        jPanel1.add(txtReleasedby, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 220, 40));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 180, 50));

        jComboBox1_Depart.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox1_Depart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here", " ", "FACULTY", "ADMIN", "HR", " " }));
        jComboBox1_Depart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBox1_Depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 220, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Department");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 100, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Branches");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 100, 30));

        jComboBox2_Branches.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox2_Branches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here ", " ", "MAIN", "MV", "BULACAN" }));
        jComboBox2_Branches.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBox2_Branches, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 220, 40));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Purposed");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, 30));

        jComboBox3_Approvedby.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox3_Approvedby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here  ", " ", "SR.DOMINA BASQUINEZ CSHT", "CRISPIN U. CABALLO" }));
        jComboBox3_Approvedby.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jComboBox3_Approvedby, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 220, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 412, 460, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 40));

        jPanel3.setBackground(new java.awt.Color(34, 49, 63));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Add_File_27px.png"))); // NOI18N
        jButton1.setText("Send");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 140, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 160, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 210, 90));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Approved By");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 100, 30));

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Edit_File_27px.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1, 150, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
      jButton1.setFont(new java.awt.Font("Century Gothic Bold", 1, 16)); // NOI18N
      jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
      jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
      jButton1.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jButton1MouseExited
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
          int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
            xx = evt.getX();
         xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
     this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
          if(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText().isEmpty()
                  ||txtQty.getText().isEmpty()
                  ||txtitem.getText().isEmpty()
                  ||jTextArea1.getText().isEmpty()
                  ||jComboBox1_Depart.getSelectedItem()=="Choose here" || jComboBox1_Depart.getSelectedItem().equals("Choose here")
                  ||jComboBox2_Branches.getSelectedItem()=="Choose here" || jComboBox2_Branches.getSelectedItem().equals("Choose here")
                  ||jComboBox3_Approvedby.getSelectedItem()=="Choose here"|| jComboBox3_Approvedby.getSelectedItem().equals("Choose here")
                  ||txtRequestedby.getText().isEmpty()
                  ||txtReleasedby.getText().isEmpty()
                  ||SignReceived.getText().isEmpty()){
                 JOptionPane.showMessageDialog(null,"This field cannot be empty!","ERROR!",JOptionPane.ERROR_MESSAGE);
          }else{
                 
           int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){  
        try {
            String sql = "INSERT INTO Log1_procure_purchaseorder "
            + "(RequestID, Date, Quantity, Item_Description, Purposed, Department, Branches, Approvedby, RequestedBy, ReleasedBy, SignReceived )"
            + "values(?,?,?,?,?,?,?,?,?,?,?)";

            pst=conn.prepareStatement(sql);
            pst.setString(1,txtRequestID.getText());
            pst.setString(2, ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());        
            pst.setString(3,txtQty.getText());
            pst.setString(4,txtitem.getText());
            pst.setString(5,jTextArea1.getText());
            
            String value1=jComboBox1_Depart.getSelectedItem().toString();
            pst.setString(6, value1);  
            String value2=jComboBox2_Branches.getSelectedItem().toString();
            pst.setString(7, value2);  
            String value3=jComboBox3_Approvedby.getSelectedItem().toString();
            pst.setString(8, value3);  
            pst.setString(9,txtRequestedby.getText());
            pst.setString(10,txtReleasedby.getText());
            pst.setString(11,SignReceived.getText());                
            pst.executeUpdate();
           purchaseOrder();
            purchaseWare() ;
            
            JOptionPane.showMessageDialog(null, "Add Successfull! ");   
            this.dispose();
            
               Toaster toasterManager = new Toaster();
               toasterManager.showToaster("New Item Received From to Purchase Order ");
               
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }   
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i + " ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){              
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtRequestIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRequestIDKeyReleased
        try{
            String sql = "SELECT * FROM Log1_procure_purchaseOrder WHERE RequestID= ? ";  
            
         pst=conn.prepareCall(sql);
             pst.setString(1,txtRequestID.getText());
         rs=pst.executeQuery();
            if(rs.next()) {
                 
                  txtRequestID.setText(rs.getString("RequestID"));
                  String add1=rs.getString("Date"); 
                 ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(add1);          
                  txtQty.setText(rs.getString("Quantity"));
                  txtitem.setText(rs.getString("Item_Description"));
                  jTextArea1.setText(rs.getString("Purposed"));
                  String r1 = rs.getString("Department");
                  jComboBox1_Depart.setSelectedItem(r1);
                   String r2 = rs.getString("Branches");
                  jComboBox2_Branches.setSelectedItem(r2);
                   String r3 = rs.getString("ApprovedBy");
                  jComboBox3_Approvedby.setSelectedItem(r3);
                  txtRequestedby.setText(rs.getString("RequestedBy"));
                   txtReleasedby.setText(rs.getString("ReleasedBy"));
                   SignReceived.setText(rs.getString("SignReceived"));
            }else{                                          
                         ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText("");               
                         txtQty.setText("");
                         txtitem.setText("");
                         jTextArea1.setText("");
                         jComboBox1_Depart.setSelectedIndex(0);
                         jComboBox2_Branches.setSelectedIndex(0);
                         jComboBox3_Approvedby.setSelectedIndex(0);
                         txtRequestedby.setText("");
                         txtReleasedby.setText("");
                         SignReceived.setText("");                       
                   }   
        }catch(SQLException e) {
        JOptionPane.showMessageDialog(null, e);      
        } 
    }//GEN-LAST:event_txtRequestIDKeyReleased

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
         jButton2.setFont(new java.awt.Font("Century Gothic Bold", 1, 16)); // NOI18N
         jButton2.setForeground(Color.white);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
      jButton2.setFont(new java.awt.Font("Century Gothic Bold", 1, 12)); // NOI18N
      jButton2.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  
            int x = JOptionPane.showConfirmDialog(null,"Are you sure you want to update?","System message!",JOptionPane.OK_OPTION); 
            
          if (x == 0) {  
            try{
            
            String value = txtRequestID.getText();
            String sql ="UPDATE Log1_procure_purchaseOrder SET RequestID=?, Date=?, Quantity=?, Item_Description=?, Purposed=?,"
                + "Department=?, Branches=?, ApprovedBy=?, RequestedBy=?, ReleasedBy=?,"
                + "SignReceived=? where RequestID="+value;
        
            pst=conn.prepareStatement(sql);
            pst.setString(1,txtRequestID.getText());
            pst.setString(2, ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());        
            pst.setString(3,txtQty.getText());
            pst.setString(4,txtitem.getText());
            pst.setString(5,jTextArea1.getText());
            
            String value1=jComboBox1_Depart.getSelectedItem().toString();
            pst.setString(6, value1);  
            String value2=jComboBox2_Branches.getSelectedItem().toString();
            pst.setString(7, value2);  
            String value3=jComboBox3_Approvedby.getSelectedItem().toString();
            pst.setString(8, value3);  
            pst.setString(9,txtRequestedby.getText());
            pst.setString(10,txtReleasedby.getText());
            pst.setString(11,SignReceived.getText());      
            pst.executeUpdate();      
            purchaseOrder();
            purchaseWare() ;
            JOptionPane.showMessageDialog(null, "Updated Successfully!");
                this.dispose();
              
        } catch (HeadlessException | SQLException e) {
              JOptionPane.showMessageDialog(null, e);
        }       
        }
    }//GEN-LAST:event_jButton2ActionPerformed
//================================================================================================== 
    public void autoID() {
     try {
         String sql = "SELECT RequestID FROM Log1_procure_purchaseOrder ORDER BY RequestID DESC";
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         if(rs.next())
         {
             String rnno = rs.getString("RequestID");
             int co = rnno.length();
             String txt = rnno.substring(0, 2);
             String num = rnno.substring(2, co);
             int n = Integer.parseInt(num);
             n++;
             String snum=Integer.toString(n);
             String ftxt=txt+snum;
             txtRequestID.setText(ftxt);
         }else{
              txtRequestID.setText("100");
         }
     } catch (NumberFormatException | SQLException e) {
         JOptionPane.showMessageDialog(rootPane, e);
     }
 }    
//==================================================================================================
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ware_RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ware_RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ware_RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ware_RequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ware_RequestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SignReceived;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1_Depart;
    private javax.swing.JComboBox<String> jComboBox2_Branches;
    private javax.swing.JComboBox<String> jComboBox3_Approvedby;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtReleasedby;
    private javax.swing.JTextField txtRequestID;
    private javax.swing.JTextField txtRequestedby;
    private javax.swing.JTextField txtitem;
    // End of variables declaration//GEN-END:variables
}
