/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Features;

import Module.ServerConnection;
import Module.Warehouse;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Jayjomjohn
 */
public class Ware_Manage_Stock extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Ware_Manage_Stock() {
        initComponents();
      conn=ServerConnection.ConnecrDb();
        
       jTable_Stock.setShowGrid(true);
       jTable_Stock.setGridColor(Color.DARK_GRAY);
       jTable_Stock.setSelectionBackground(Color.lightGray);
       
       JTableHeader th = jTable_Stock.getTableHeader();
       th.setForeground(Color.BLACK);
       th.setFont(new Font("Century Gothic", Font.BOLD, 14));
       
      stockables();
     
    }
//====================================================================================
 public void stockables() {  
         try{
            String sql ="SELECT * FROM Log1_ware_addstock";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable_Stock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
             }
       catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }       
    } 
//====================================================================================

  public void waretable() {
            DefaultTableModel model = (DefaultTableModel) Warehouse.jTable_stocklistinfo.getModel(); 
        try{
            String sql ="SELECT * FROM Log1_ware_addstock";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Warehouse.jTable_stocklistinfo.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
             }catch(SQLException e) {
          JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }  
//====================================================================================  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBody = new javax.swing.JPanel();
        Sidepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        exit = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox_source = new javax.swing.JComboBox<>();
        service_life = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        subcat = new javax.swing.JTextField();
        jComboBox_category = new javax.swing.JComboBox<>();
        jComboBox_branches = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Stock = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Clear = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Edit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Update = new javax.swing.JButton();
        stock_id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        PanelBody.setBackground(new java.awt.Color(255, 255, 255));
        PanelBody.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        PanelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidepanel.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout SidepanelLayout = new javax.swing.GroupLayout(Sidepanel);
        Sidepanel.setLayout(SidepanelLayout);
        SidepanelLayout.setHorizontalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        SidepanelLayout.setVerticalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        PanelBody.add(Sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 540));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Manage Stock");
        PanelBody.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 30));
        PanelBody.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1030, 10));

        exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        PanelBody.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 40, 33));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel18.setText("Branches");
        PanelBody.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 85, 25));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Category");
        PanelBody.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 85, 25));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Sub-Category");
        PanelBody.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 85, 25));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Cost");
        PanelBody.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, 25));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Brand");
        PanelBody.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 60, 25));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Service Life");
        PanelBody.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 25));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Source");
        PanelBody.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 60, 25));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel16.setText("Service Date");
        PanelBody.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 80, 25));
        PanelBody.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 160, -1));

        jComboBox_source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here:", "Purchase", "Return" }));
        PanelBody.add(jComboBox_source, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 160, -1));

        service_life.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PanelBody.add(service_life, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 160, -1));

        brand.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PanelBody.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 160, -1));

        txtCost.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCost.setToolTipText("Enter Your Cost ");
        txtCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostKeyTyped(evt);
            }
        });
        PanelBody.add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, -1));

        subcat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PanelBody.add(subcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, -1));

        jComboBox_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here:", "Computer", "Furniture", "Stationary", "Electronics", "Others" }));
        PanelBody.add(jComboBox_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 160, -1));

        jComboBox_branches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose here", " ", "Main", "Bulacan", "MV" }));
        PanelBody.add(jComboBox_branches, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 160, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Stock");
        PanelBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 85, 25));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        PanelBody.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 369, 260, 60));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Purposed");
        PanelBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 85, 25));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        PanelBody.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 459, 260, 60));

        jTable_Stock.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTable_Stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_Stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_StockMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_Stock);

        PanelBody.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 740, 350));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        Clear.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(204, 204, 204));
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Erase_25px.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.setContentAreaFilled(false);
        Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClearMouseExited(evt);
            }
        });
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 120, 50));
        PanelBody.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 740, 10));

        jPanel2.setBackground(new java.awt.Color(103, 65, 114));
        jPanel2.setToolTipText("");

        Edit.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Edit.setForeground(new java.awt.Color(204, 204, 204));
        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Edit_26px.png"))); // NOI18N
        Edit.setText("Edit");
        Edit.setContentAreaFilled(false);
        Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditMouseExited(evt);
            }
        });
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBody.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 120, 50));

        jPanel4.setBackground(new java.awt.Color(30, 130, 76));

        Update.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Update.setForeground(new java.awt.Color(204, 204, 204));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Edit_File_27px.png"))); // NOI18N
        Update.setText("Update");
        Update.setContentAreaFilled(false);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateMouseExited(evt);
            }
        });
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBody.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 120, 50));

        stock_id.setEditable(false);
        stock_id.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        stock_id.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock ID"));
        stock_id.setOpaque(false);
        stock_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stock_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stock_idFocusLost(evt);
            }
        });
        PanelBody.add(stock_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 200, 40));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel15.setText("Description");
        PanelBody.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 85, 25));
        PanelBody.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 160, 30));

        getContentPane().add(PanelBody);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        dispose();
    }//GEN-LAST:event_exitMouseClicked
int xx,xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    xx = evt.getX();
    xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseEntered
    Edit.setFont(new java.awt.Font("Century Gothic", 1, 16)); 
    Edit.setForeground(Color.white);
    }//GEN-LAST:event_EditMouseEntered

    private void EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseExited
    Edit.setFont(new java.awt.Font("Century Gothic", 1, 12)); 
    Edit.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_EditMouseExited

    private void UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseEntered
    Update.setFont(new java.awt.Font("Century Gothic", 1, 16));
    Update.setForeground(Color.white);
    }//GEN-LAST:event_UpdateMouseEntered

    private void UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseExited
    Update.setFont(new java.awt.Font("Century Gothic", 1, 12)); 
    Update.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_UpdateMouseExited

    private void ClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseEntered
    Clear.setFont(new java.awt.Font("Century Gothic", 1, 16));
    Clear.setForeground(Color.white);
    }//GEN-LAST:event_ClearMouseEntered

    private void ClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseExited
    Clear.setFont(new java.awt.Font("Century Gothic", 1, 12)); 
    Clear.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_ClearMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    
       //Disable Textfield & ComboBox
       jComboBox_branches.setEnabled(false);
       jComboBox_category.setEnabled(false);
       subcat.setEnabled(false);
       txtCost.setEnabled(false);
       brand.setEnabled(false);
       service_life.setEnabled(false);
       stock.setEnabled(false);
       jComboBox_source.setEnabled(false);
       jDateChooser1.setEnabled(false);
       jTextArea1.setEnabled(false);
       jTextArea2.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
    //Show Button
    Edit.setEnabled(false);
 
    //Show TextField & ComboBox
       jComboBox_branches.setEnabled(true);
       jComboBox_category.setEnabled(true);
       subcat.setEnabled(true);
       txtCost.setEnabled(true);
       brand.setEnabled(true);
       service_life.setEnabled(true);
       stock.setEnabled(true);
       jComboBox_source.setEnabled(true);
       jDateChooser1.setEnabled(true);
       jTextArea1.setEnabled(true);
       jTextArea2.setEnabled(true);         
    }//GEN-LAST:event_EditActionPerformed

    private void txtCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostKeyTyped
           if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtCostKeyTyped

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
     int x = JOptionPane.showConfirmDialog(null,"DO YOU REALLY WANT TO UPDATE?","UPDATED",JOptionPane.YES_NO_OPTION);
       if(x==0){   
        try{
        int row =jTable_Stock.getSelectedRow();
        String value = (jTable_Stock.getModel().getValueAt(row, 0).toString());
        String sql ="UPDATE Log1_ware_addstock SET Stock_ID=?, Branches=?, Category=?, Sub_category=?, Cost=?, Brand=?, Service_Life=?, Source=?, Service_Date=?, "
                + " Stock=?, Description=?, Purposed=?  where Stock_id="+value;
        pst=conn.prepareStatement(sql);
        
             pst.setString(1,stock_id.getText());
            String value1=jComboBox_branches.getSelectedItem().toString();
            pst.setString(2, value1);  
            
            String value2=jComboBox_category.getSelectedItem().toString();
            pst.setString(3, value2);             
            pst.setString(4,subcat.getText());
            pst.setString(5,txtCost.getText());
            pst.setString(6,brand.getText());
            pst.setString(7,service_life.getText());
            
            String value3=jComboBox_source.getSelectedItem().toString();
            pst.setString(8, value3);
            pst.setString(9, ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            
            pst.setString(10,stock.getText());
            pst.setString(11,jTextArea1.getText());
            pst.setString(12,jTextArea2.getText());
                
            pst.executeUpdate();
             stockables();
             waretable() ;
            JOptionPane.showMessageDialog(null, "Updated Successfully!");
            this.dispose();
        } catch (HeadlessException | SQLException e) {
              JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void jTable_StockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_StockMouseClicked
         DefaultTableModel model = (DefaultTableModel) jTable_Stock.getModel(); 
   
        try{
            int row = jTable_Stock.getSelectedRow();
            String Table_click=(jTable_Stock.getModel().getValueAt(row,0).toString());
     
            String sql = "select * from Log1_ware_addstock where Stock_id='"+Table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()) {
                
            String a = rs.getString("Stock_ID");
            stock_id.setText(a);
            String add1 = rs.getString("Branches");
            jComboBox_branches.setSelectedItem(add1);
            String add2 = rs.getString("Category");
            jComboBox_category.setSelectedItem(add2);
            String add3 = rs.getString("Sub_Category");
            subcat.setText(add3);
            String add4 = rs.getString("Cost");
            txtCost.setText(add4);
            String add5 = rs.getString("Brand");
            brand.setText(add5);
            String add6 = rs.getString("Service_Life");
            service_life.setText(add6);
            String add7 = rs.getString("Source");
            jComboBox_source.setSelectedItem(add7);
            String add8=rs.getString("Service_Date"); 
            
            String q = rs.getString("stock");
            stock.setText(q);
            
            ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(add8);
            String add9 = rs.getString("Description");
            jTextArea1.setText(add9);
            String add10 = rs.getString("Purposed");
            jTextArea2.setText(add10);
            }     
        }catch(SQLException e) {
        JOptionPane.showMessageDialog(null, e);      
        } 
    }//GEN-LAST:event_jTable_StockMouseClicked

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
      stock_id.setText("");
      jComboBox_branches.setSelectedIndex(0);
      jComboBox_category.setSelectedIndex(0);
      subcat.setText("");
      txtCost.setText("");
      brand.setText("");
      service_life.setText("");
      jComboBox_source.setSelectedIndex(0);
      jDateChooser1.setDate(null);
      jTextArea1.setText("");
      jTextArea2.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void stock_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stock_idFocusGained
        if(stock_id.getText().trim().toLowerCase().equals("stocknumber")){
        stock_id.setText("");
        stock_id.setForeground(Color.BLACK);
     }
    }//GEN-LAST:event_stock_idFocusGained

    private void stock_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stock_idFocusLost
        if(stock_id.getText().trim().equals("")|| 
        stock_id.getText().trim().toLowerCase().equals("stocknumber")){
        
        stock_id.setText("Stocknumber");
        stock_id.setForeground(Color.DARK_GRAY);
     }
    }//GEN-LAST:event_stock_idFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i +" ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){              
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ware_Manage_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ware_Manage_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ware_Manage_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ware_Manage_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ware_Manage_Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Edit;
    private javax.swing.JPanel PanelBody;
    private javax.swing.JPanel Sidepanel;
    private javax.swing.JButton Update;
    private javax.swing.JTextField brand;
    private javax.swing.JLabel exit;
    private javax.swing.JComboBox<String> jComboBox_branches;
    private javax.swing.JComboBox<String> jComboBox_category;
    private javax.swing.JComboBox<String> jComboBox_source;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JTable jTable_Stock;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField service_life;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField stock_id;
    private javax.swing.JTextField subcat;
    private javax.swing.JTextField txtCost;
    // End of variables declaration//GEN-END:variables
}
