/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Jayjomjohn
 */
public class MainFrame extends javax.swing.JFrame {

    GridBagLayout a = new GridBagLayout();
    
    PM frame1;
    Procurement frame2;
    Asset frame3;
    Warehouse frame4;
    
    public MainFrame() {
        initComponents();    
        this.setExtendedState(MainFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        
        ImageIcon ic = new ImageIcon(getClass().getResource("/Module/icons8_Truck_100px_1.png"));
        this.setIconImage(ic.getImage());  
        
        Showtime();
              
        frame1 = new PM();
        frame2 = new Procurement();
        frame3 = new Asset();
        frame4 = new Warehouse();
        
        Panelchanger.setLayout(a);
        GridBagConstraints GBC = new GridBagConstraints();
        GBC.gridx = 0;
        GBC.gridy = 0;
        
        Panelchanger.add(frame1,GBC);
        Panelchanger.add(frame2,GBC);
        Panelchanger.add(frame3,GBC);
        Panelchanger.add(frame4,GBC);
        
        frame1.setVisible(false);
        frame2.setVisible(false);
        frame3.setVisible(false);
        frame4.setVisible(false);
       
        
    }
  private void Showtime() {
    java.util.Date d =new java.util.Date();
    SimpleDateFormat dd = new SimpleDateFormat("EEE LLL/dd/yyyy");
    Date.setText(dd.format(d));
       
    new Timer(0, (ActionEvent e) -> {
    java.util.Date d1 = new java.util.Date();
    SimpleDateFormat dd1 = new SimpleDateFormat("hh:mm:ss aa");
    Time.setText(dd1.format(d1));
  
}).start();       
}  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBody = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Panelchanger = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        SubModule = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TimePanel = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        Time = new javax.swing.JTextField();
        DatePanel = new javax.swing.JPanel();
        Date = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1365, 761));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1365, 761));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenu.setBackground(new java.awt.Color(0, 51, 102));
        PanelMenu.setOpaque(false);
        PanelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMenuMouseExited(evt);
            }
        });
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Manager_30px.png"))); // NOI18N
        jLabel1.setText("PROJECT MANAGEMENT");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        PanelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 260, 42));

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Procurement_30px.png"))); // NOI18N
        jLabel2.setText("PROCUREMENT");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        PanelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 42));

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Product_30px.png"))); // NOI18N
        jLabel3.setText("ASSET MANAGEMENT");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        PanelMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 42));

        jLabel4.setBackground(new java.awt.Color(0, 51, 102));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Warehouse_30px.png"))); // NOI18N
        jLabel4.setText("WAREHOUSE");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        PanelMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, 42));

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Exit_30px.png"))); // NOI18N
        jLabel5.setText("Sign-Out");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        PanelMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 260, 42));

        PanelBody.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 280, 20));

        Panelchanger.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        Panelchanger.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panelchanger.setMaximumSize(new java.awt.Dimension(1340, 580));
        Panelchanger.setMinimumSize(new java.awt.Dimension(1340, 580));
        Panelchanger.setOpaque(false);
        Panelchanger.setRequestFocusEnabled(false);
        Panelchanger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelchangerMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout PanelchangerLayout = new javax.swing.GroupLayout(Panelchanger);
        Panelchanger.setLayout(PanelchangerLayout);
        PanelchangerLayout.setHorizontalGroup(
            PanelchangerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1336, Short.MAX_VALUE)
        );
        PanelchangerLayout.setVerticalGroup(
            PanelchangerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        PanelBody.add(Panelchanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1340, 610));

        Header.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        Header.setOpaque(false);
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubModule.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        SubModule.setForeground(new java.awt.Color(204, 204, 204));
        SubModule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubModule.setText("/ DashBoard /");
        SubModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubModuleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubModuleMouseExited(evt);
            }
        });
        Header.add(SubModule, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 400, 50));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Delivery_30px.png"))); // NOI18N
        jButton1.setText("LOGISTICS 1");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Delivery_30px_1.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Header.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 274, 42));

        TimePanel.setBackground(new java.awt.Color(37, 116, 169));
        TimePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        TimePanel.setOpaque(false);

        time.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(204, 204, 204));
        time.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Clock_25px_1.png"))); // NOI18N
        time.setText("Time Today");

        Time.setEditable(false);
        Time.setBackground(new java.awt.Color(0, 51, 102));
        Time.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Time.setForeground(new java.awt.Color(204, 204, 204));
        Time.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Time.setBorder(null);
        Time.setOpaque(false);
        Time.setSelectionColor(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout TimePanelLayout = new javax.swing.GroupLayout(TimePanel);
        TimePanel.setLayout(TimePanelLayout);
        TimePanelLayout.setHorizontalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Time, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        TimePanelLayout.setVerticalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Time)
            .addGroup(TimePanelLayout.createSequentialGroup()
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Header.add(TimePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 270, 40));

        DatePanel.setBackground(new java.awt.Color(37, 116, 169));
        DatePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        DatePanel.setOpaque(false);

        Date.setEditable(false);
        Date.setBackground(new java.awt.Color(0, 51, 102));
        Date.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Date.setForeground(new java.awt.Color(204, 204, 204));
        Date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date.setBorder(null);
        Date.setOpaque(false);
        Date.setSelectionColor(new java.awt.Color(0, 51, 102));

        date.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(204, 204, 204));
        date.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Date_To_25px.png"))); // NOI18N
        date.setText("Date Today");

        javax.swing.GroupLayout DatePanelLayout = new javax.swing.GroupLayout(DatePanel);
        DatePanel.setLayout(DatePanelLayout);
        DatePanelLayout.setHorizontalGroup(
            DatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatePanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        DatePanelLayout.setVerticalGroup(
            DatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Header.add(DatePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 10, 330, 40));

        PanelBody.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1340, 70));

        Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Minimize_Window_25px.png"))); // NOI18N
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });
        PanelBody.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 30, 30));

        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Cancel_25px.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        PanelBody.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 30, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/bag1.jpg"))); // NOI18N
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackgroundMouseEntered(evt);
            }
        });
        PanelBody.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1360, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainFrame m = new MainFrame();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BackgroundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseEntered
        PanelMenu.setSize(0, 0);
    }//GEN-LAST:event_BackgroundMouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        PanelMenu.setSize(270, 340);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        PanelMenu.setSize(0, 0);
    }//GEN-LAST:event_jButton1MouseExited

    private void PanelMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMouseEntered
        PanelMenu.setSize(270, 340);
    }//GEN-LAST:event_PanelMenuMouseEntered

    private void PanelMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMenuMouseExited
      
    }//GEN-LAST:event_PanelMenuMouseExited

    private void PanelchangerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelchangerMouseEntered
       PanelMenu.setSize(0, 0);
    }//GEN-LAST:event_PanelchangerMouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        SubModule.setText("PROJECT MANAGEMENT");
        frame1.setVisible(true);
        frame2.setVisible(false);
        frame3.setVisible(false);
        frame4.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        SubModule.setText("PROCUREMENT");
        frame1.setVisible(false);
        frame2.setVisible(true);
        frame3.setVisible(false);
        frame4.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        SubModule.setText("ASSET MANAGEMENT");
        frame1.setVisible(false);
        frame2.setVisible(false);
        frame3.setVisible(true);
        frame4.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
int x = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","System message!",JOptionPane.YES_NO_OPTION);
    if (x==0) {    
      
        LoginKo L = new LoginKo();
        L.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        SubModule.setText("WAREHOUSE");
        frame1.setVisible(false);
        frame2.setVisible(false);
        frame3.setVisible(false);
        frame4.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked
  public void setforeground(JLabel label){
        label.setForeground(new Color(255,255,255));
    }
    public void resetForegound(JLabel label){
        label.setForeground(new Color(204,204,204));
    }
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        setforeground(jLabel1);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        resetForegound(jLabel1);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        setforeground(jLabel2);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        resetForegound(jLabel2);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        setforeground(jLabel3);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        resetForegound(jLabel3);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        setforeground(jLabel4);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        resetForegound(jLabel4);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
       jLabel5.setForeground(Color.red);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        resetForegound(jLabel5);
    }//GEN-LAST:event_jLabel5MouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
      this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void SubModuleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubModuleMouseEntered
    SubModule.setFont(new java.awt.Font("Century Gothic Bold", 1, 30));
    SubModule.setForeground(Color.white);
    }//GEN-LAST:event_SubModuleMouseEntered

    private void SubModuleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubModuleMouseExited
    SubModule.setFont(new java.awt.Font("Century Gothic", 1, 24));
    SubModule.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_SubModuleMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          for (double i = 0.0; i <= 1.0; i = i +0.1) {
            String  val = i +" ";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(InterruptedException e){          
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       jLabel2.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
            }

            }
            
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField Date;
    private javax.swing.JPanel DatePanel;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Minimize;
    private javax.swing.JPanel PanelBody;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel Panelchanger;
    private javax.swing.JLabel SubModule;
    private javax.swing.JTextField Time;
    private javax.swing.JPanel TimePanel;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

    void User(String username) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
