/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Jayjomjohn
 */
public class PM extends javax.swing.JPanel {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public PM() {
        initComponents();
        conn=ServerConnection.ConnecrDb();
     
          
          allproject();
          Requestmaterials();
          projectrisk();
          requestpm() ;
          projecttimeline();
//          budgethistory();
    }
    
//   public void budgethistory() {
//
//           String a = "ProjectManagement";
//        try{
//            String sql ="SELECT Request_No, budget_description, date_requested FROM finance_budgetrequest where department like  '"+a+"' ";
//            pst=conn.prepareStatement(sql);
//            rs=pst.executeQuery();
//            jTable_Budget.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
//             }catch(SQLException e) {
//          JOptionPane.showMessageDialog(this, e.getMessage());
//        }
//  }        
//    
//==================================================================================================
   public final void projecttimeline() {
        try{
            String sql = "SELECT * FROM Log1_projecttimeline ";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable6.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){        
        }
}             
//==================================================================================================   
  public final void requestpm() {
        try{
            String sql = "SELECT * FROM Log1_Requestpm ";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){        
        }
}       
//==================================================================================================
public final void allproject() {
        try{
            String sql = "SELECT * FROM Log1_project ";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable_ProjectList.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){        
        }
}     
//==================================================================================================
 public final void Requestmaterials() {
        try{
            String sql = "SELECT * FROM Log1_Requestmaterials";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable2.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){        
        }
}            
//================================================================================================== 
 public final void projectrisk() {
        try{
            String sql = "SELECT * FROM Log1_projectrisk";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tablerisk.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){        
        }
}          
//================================================================================================== 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTN1 = new javax.swing.JPanel();
        PN1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BTN2 = new javax.swing.JPanel();
        PN2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BTN3 = new javax.swing.JPanel();
        PN3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BTN4 = new javax.swing.JPanel();
        PN4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BTN5 = new javax.swing.JPanel();
        PN5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelBody = new javax.swing.JPanel();
        ProjectTimeline = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        priority = new javax.swing.JTextField();
        taskname = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        projectname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        ProjectList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        Search = new javax.swing.JTextField();
        ProjectRisk = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton_addrisk = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        manage = new javax.swing.JButton();
        Request = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        Receiveditem = new javax.swing.JPanel();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        Ware = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Finance = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Vendor = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Legal = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Warehouse = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel17 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1330, 580));
        setMinimumSize(new java.awt.Dimension(1330, 580));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        SidePanel.setMaximumSize(new java.awt.Dimension(250, 510));
        SidePanel.setMinimumSize(new java.awt.Dimension(250, 510));
        SidePanel.setOpaque(false);
        SidePanel.setPreferredSize(new java.awt.Dimension(250, 510));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Admin_100px.png"))); // NOI18N
        SidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 13, 130, -1));

        BTN1.setBackground(new java.awt.Color(0, 102, 153));
        BTN1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        BTN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTN1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTN1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout PN1Layout = new javax.swing.GroupLayout(PN1);
        PN1.setLayout(PN1Layout);
        PN1Layout.setHorizontalGroup(
            PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PN1Layout.setVerticalGroup(
            PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Planner_35px.png"))); // NOI18N
        jLabel2.setText("Project Timeline");

        javax.swing.GroupLayout BTN1Layout = new javax.swing.GroupLayout(BTN1);
        BTN1.setLayout(BTN1Layout);
        BTN1Layout.setHorizontalGroup(
            BTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN1Layout.createSequentialGroup()
                .addComponent(PN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 211, Short.MAX_VALUE))
            .addGroup(BTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BTN1Layout.createSequentialGroup()
                    .addContainerGap(22, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        BTN1Layout.setVerticalGroup(
            BTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BTN1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        SidePanel.add(BTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 132, 230, 70));

        BTN2.setBackground(new java.awt.Color(34, 49, 63));
        BTN2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        BTN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTN2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTN2MousePressed(evt);
            }
        });

        PN2.setOpaque(false);

        javax.swing.GroupLayout PN2Layout = new javax.swing.GroupLayout(PN2);
        PN2.setLayout(PN2Layout);
        PN2Layout.setHorizontalGroup(
            PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PN2Layout.setVerticalGroup(
            PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Project_30px.png"))); // NOI18N
        jLabel3.setText("Project List");

        javax.swing.GroupLayout BTN2Layout = new javax.swing.GroupLayout(BTN2);
        BTN2.setLayout(BTN2Layout);
        BTN2Layout.setHorizontalGroup(
            BTN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN2Layout.createSequentialGroup()
                .addComponent(PN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 211, Short.MAX_VALUE))
            .addGroup(BTN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BTN2Layout.createSequentialGroup()
                    .addContainerGap(20, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );
        BTN2Layout.setVerticalGroup(
            BTN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BTN2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        SidePanel.add(BTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 230, 70));

        BTN3.setBackground(new java.awt.Color(34, 49, 63));
        BTN3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        BTN3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTN3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTN3MousePressed(evt);
            }
        });

        PN3.setOpaque(false);

        javax.swing.GroupLayout PN3Layout = new javax.swing.GroupLayout(PN3);
        PN3.setLayout(PN3Layout);
        PN3Layout.setHorizontalGroup(
            PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PN3Layout.setVerticalGroup(
            PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Attention_30px.png"))); // NOI18N
        jLabel4.setText("Project Risk");

        javax.swing.GroupLayout BTN3Layout = new javax.swing.GroupLayout(BTN3);
        BTN3.setLayout(BTN3Layout);
        BTN3Layout.setHorizontalGroup(
            BTN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN3Layout.createSequentialGroup()
                .addComponent(PN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(BTN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BTN3Layout.createSequentialGroup()
                    .addContainerGap(20, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );
        BTN3Layout.setVerticalGroup(
            BTN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BTN3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        SidePanel.add(BTN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 230, 70));

        BTN4.setBackground(new java.awt.Color(34, 49, 63));
        BTN4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        BTN4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTN4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTN4MousePressed(evt);
            }
        });

        PN4.setOpaque(false);

        javax.swing.GroupLayout PN4Layout = new javax.swing.GroupLayout(PN4);
        PN4.setLayout(PN4Layout);
        PN4Layout.setHorizontalGroup(
            PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PN4Layout.setVerticalGroup(
            PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Workspace_30px.png"))); // NOI18N
        jLabel5.setText("Request");

        javax.swing.GroupLayout BTN4Layout = new javax.swing.GroupLayout(BTN4);
        BTN4.setLayout(BTN4Layout);
        BTN4Layout.setHorizontalGroup(
            BTN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN4Layout.createSequentialGroup()
                .addComponent(PN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(BTN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BTN4Layout.createSequentialGroup()
                    .addContainerGap(22, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)))
        );
        BTN4Layout.setVerticalGroup(
            BTN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BTN4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        SidePanel.add(BTN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 230, 70));

        BTN5.setBackground(new java.awt.Color(34, 49, 63));
        BTN5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        BTN5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTN5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTN5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTN5MousePressed(evt);
            }
        });

        PN5.setOpaque(false);

        javax.swing.GroupLayout PN5Layout = new javax.swing.GroupLayout(PN5);
        PN5.setLayout(PN5Layout);
        PN5Layout.setHorizontalGroup(
            PN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PN5Layout.setVerticalGroup(
            PN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Incoming_Data_35px.png"))); // NOI18N
        jLabel6.setText("Received Item");

        javax.swing.GroupLayout BTN5Layout = new javax.swing.GroupLayout(BTN5);
        BTN5.setLayout(BTN5Layout);
        BTN5Layout.setHorizontalGroup(
            BTN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTN5Layout.createSequentialGroup()
                .addComponent(PN5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(BTN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BTN5Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        BTN5Layout.setVerticalGroup(
            BTN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PN5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BTN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BTN5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        SidePanel.add(BTN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 230, 70));

        add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 558));

        PanelBody.setMaximumSize(new java.awt.Dimension(1040, 560));
        PanelBody.setMinimumSize(new java.awt.Dimension(1040, 560));
        PanelBody.setOpaque(false);
        PanelBody.setLayout(new java.awt.CardLayout());

        ProjectTimeline.setBackground(new java.awt.Color(255, 255, 255));
        ProjectTimeline.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)), "Project TimeLine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        ProjectTimeline.setOpaque(false);
        ProjectTimeline.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        jPanel26.setOpaque(false);
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable6);

        jPanel26.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 540, 490));

        ProjectTimeline.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 560, 510));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        priority.setEditable(false);
        priority.setBackground(new java.awt.Color(255, 255, 255));
        priority.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        priority.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Priority", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel3.add(priority, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 180, 50));

        taskname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        taskname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Task Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel3.add(taskname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 410, 50));

        jPanel4.setBackground(new java.awt.Color(34, 49, 63));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Add_File_27px.png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 410, 60));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Project Description");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 30));

        jDateChooser1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 330, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("End");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 60, 30));

        jDateChooser2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel3.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 330, 30));

        projectname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        projectname.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Your Project Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        projectname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                projectnameKeyReleased(evt);
            }
        });
        jPanel3.add(projectname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 50));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 270, 70));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Start ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, 30));

        ProjectTimeline.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 440, 510));

        PanelBody.add(ProjectTimeline, "card2");

        ProjectList.setBackground(new java.awt.Color(204, 204, 204));
        ProjectList.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)), "Project List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        ProjectList.setOpaque(false);
        ProjectList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_ProjectList.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTable_ProjectList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_ProjectList);

        ProjectList.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 93, 1010, 450));

        jPanel6.setBackground(new java.awt.Color(58, 83, 155));

        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 204, 204));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Form_27px.png"))); // NOI18N
        jButton6.setText("Add Project");
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ProjectList.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 160, 50));

        jPanel14.setBackground(new java.awt.Color(58, 83, 155));

        jButton12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(204, 204, 204));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Update_User_35px.png"))); // NOI18N
        jButton12.setText("Manage");
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton12MouseExited(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ProjectList.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 150, 50));

        Search.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(204, 204, 204));
        Search.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        Search.setOpaque(false);
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });
        ProjectList.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, 240, -1));

        PanelBody.add(ProjectList, "card3");

        ProjectRisk.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)), "Project risk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        ProjectRisk.setOpaque(false);
        ProjectRisk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablerisk.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tablerisk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablerisk);

        ProjectRisk.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 103, 1000, 430));

        jPanel7.setBackground(new java.awt.Color(58, 83, 155));

        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 204, 204));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Printer_27px.png"))); // NOI18N
        jButton7.setText("Print Table");
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ProjectRisk.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 150, 50));

        jPanel9.setBackground(new java.awt.Color(58, 83, 155));

        jButton_addrisk.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton_addrisk.setForeground(new java.awt.Color(204, 204, 204));
        jButton_addrisk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_High_Priority_35px.png"))); // NOI18N
        jButton_addrisk.setText("Add Risk");
        jButton_addrisk.setContentAreaFilled(false);
        jButton_addrisk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_addrisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addriskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_addrisk, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_addrisk, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ProjectRisk.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 160, 50));

        jPanel13.setBackground(new java.awt.Color(58, 83, 155));

        manage.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        manage.setForeground(new java.awt.Color(204, 204, 204));
        manage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Update_User_35px.png"))); // NOI18N
        manage.setText("Manage");
        manage.setContentAreaFilled(false);
        manage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manage, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manage, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ProjectRisk.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 150, 50));

        PanelBody.add(ProjectRisk, "card4");

        Request.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)), "Request", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        Request.setOpaque(false);
        Request.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(58, 83, 155));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton17.setForeground(new java.awt.Color(204, 204, 204));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Trolley_27px.png"))); // NOI18N
        jButton17.setText("Request Materials");
        jButton17.setContentAreaFilled(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setMaximumSize(new java.awt.Dimension(83, 25));
        jButton17.setMinimumSize(new java.awt.Dimension(83, 25));
        jButton17.setPreferredSize(new java.awt.Dimension(83, 25));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 60));

        Request.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 230, 60));

        jPanel21.setBackground(new java.awt.Color(58, 83, 155));

        jButton18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(204, 204, 204));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Sales_Performance_35px_1.png"))); // NOI18N
        jButton18.setText("Request Budget");
        jButton18.setContentAreaFilled(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setMaximumSize(new java.awt.Dimension(83, 25));
        jButton18.setMinimumSize(new java.awt.Dimension(83, 25));
        jButton18.setPreferredSize(new java.awt.Dimension(83, 25));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Request.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 190, 60));

        jPanel22.setBackground(new java.awt.Color(58, 83, 155));

        jButton19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton19.setForeground(new java.awt.Color(204, 204, 204));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Documents_35px.png"))); // NOI18N
        jButton19.setText("Request Contract");
        jButton19.setContentAreaFilled(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.setMaximumSize(new java.awt.Dimension(83, 25));
        jButton19.setMinimumSize(new java.awt.Dimension(83, 25));
        jButton19.setPreferredSize(new java.awt.Dimension(83, 25));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Request.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 190, 60));

        jPanel11.setBackground(new java.awt.Color(58, 83, 155));

        jButton20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton20.setForeground(new java.awt.Color(204, 204, 204));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Handshake_35px.png"))); // NOI18N
        jButton20.setText("Request Contractor");
        jButton20.setContentAreaFilled(false);
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.setMaximumSize(new java.awt.Dimension(83, 25));
        jButton20.setMinimumSize(new java.awt.Dimension(83, 25));
        jButton20.setPreferredSize(new java.awt.Dimension(83, 25));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Request.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 240, 60));

        PanelBody.add(Request, "card5");

        Receiveditem.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)), "Received", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        Receiveditem.setOpaque(false);
        Receiveditem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSlider1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        jPanelSlider1.setOpaque(false);

        Ware.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)), "Request Materials", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        Ware.setOpaque(false);
        Ware.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        Ware.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 58, 960, 370));

        jPanelSlider1.add(Ware, "card2");

        Finance.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)), "Request Budget", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        Finance.setOpaque(false);
        Finance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Budget.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTable_Budget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable_Budget);

        Finance.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 85, 970, 340));

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Module/icons/icons8_Refresh_27px.png"))); // NOI18N
        jButton2.setText("Refresh");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 30));

        Finance.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 170, 50));

        jPanelSlider1.add(Finance, "card3");

        Vendor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)), "Request Contractor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        Vendor.setOpaque(false);
        Vendor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        Vendor.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 35, 980, 390));

        jPanelSlider1.add(Vendor, "card4");

        Legal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)), "Request of Contract", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        Legal.setOpaque(false);
        Legal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable5);

        Legal.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 47, 970, 380));

        jPanelSlider1.add(Legal, "card5");

        Warehouse.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 153), new java.awt.Color(0, 102, 153)), "Request Warehouse", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 16), new java.awt.Color(204, 204, 204))); // NOI18N
        Warehouse.setOpaque(false);
        Warehouse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable1);

        Warehouse.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 30, 960, 390));

        jPanelSlider1.add(Warehouse, "card6");

        Receiveditem.add(jPanelSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 96, 1010, 450));

        jPanel17.setBackground(new java.awt.Color(58, 83, 155));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(204, 204, 204));
        jButton13.setText("Request Contract ");
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 40));

        Receiveditem.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 180, 60));

        jPanel18.setBackground(new java.awt.Color(58, 83, 155));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(204, 204, 204));
        jButton14.setText("Request Materials ");
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 40));

        Receiveditem.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 60));

        jPanel19.setBackground(new java.awt.Color(58, 83, 155));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(204, 204, 204));
        jButton15.setText("Request Budget ");
        jButton15.setContentAreaFilled(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 40));

        Receiveditem.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 170, 60));

        jPanel20.setBackground(new java.awt.Color(58, 83, 155));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(204, 204, 204));
        jButton16.setText("Request Contractor ");
        jButton16.setContentAreaFilled(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        Receiveditem.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 190, 60));

        jPanel1.setBackground(new java.awt.Color(58, 83, 155));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Request Warehouse");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 170, 38));

        Receiveditem.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 190, 60));

        PanelBody.add(Receiveditem, "card6");

        add(PanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 1040, 560));
    }// </editor-fold>//GEN-END:initComponents

    public void setColor (JPanel pane) {
        pane.setBackground(new Color(58, 83, 155)); 
    }
    public void resetColor(JPanel []pane, JPanel[] indicators)
    {
        for (int i=0; i<pane.length; i++) {
           pane[i].setBackground(new Color(34,49,63));           
        }for (int i=0; i<indicators.length; i++) {
           indicators[i].setOpaque(false);
        }
    }   
    private void BTN1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN1MousePressed
        setColor(BTN1);
        PN1.setOpaque(true);
        resetColor(new JPanel[]{BTN2,BTN3,BTN4,BTN5},new JPanel[]{PN2,PN3,PN4,PN5});    
    }//GEN-LAST:event_BTN1MousePressed

    private void BTN2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN2MousePressed
        setColor(BTN2);
        PN2.setOpaque(true);
        resetColor(new JPanel[]{BTN1,BTN3,BTN4,BTN5},new JPanel[]{PN1,PN3,PN4,PN5});
    }//GEN-LAST:event_BTN2MousePressed

    private void BTN3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN3MousePressed
        setColor(BTN3);
        PN3.setOpaque(true);
        resetColor(new JPanel[]{BTN1,BTN2,BTN4,BTN5},new JPanel[]{PN1,PN2,PN4,PN5});
    }//GEN-LAST:event_BTN3MousePressed

    private void BTN4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN4MousePressed
        setColor(BTN4);
        PN4.setOpaque(true);
        resetColor(new JPanel[]{BTN1,BTN2,BTN3,BTN5},new JPanel[]{PN1,PN2,PN3,PN5});
    }//GEN-LAST:event_BTN4MousePressed

    private void BTN5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN5MousePressed
        setColor(BTN5);
        PN5.setOpaque(true);
        resetColor(new JPanel[]{BTN1,BTN2,BTN3,BTN4},new JPanel[]{PN1,PN2,PN3,PN4});
    }//GEN-LAST:event_BTN5MousePressed

    private void BTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN1MouseClicked
    PanelBody.removeAll();
    PanelBody.repaint();
    PanelBody.revalidate();
    PanelBody.add(ProjectTimeline);
    PanelBody.repaint();
    PanelBody.revalidate();
    }//GEN-LAST:event_BTN1MouseClicked

    private void BTN2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN2MouseClicked
    PanelBody.removeAll();
    PanelBody.repaint();
    PanelBody.revalidate();
    PanelBody.add(ProjectList);
    PanelBody.repaint();
    PanelBody.revalidate();
    }//GEN-LAST:event_BTN2MouseClicked

    private void BTN3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN3MouseClicked
    PanelBody.removeAll();
    PanelBody.repaint();
    PanelBody.revalidate();
    PanelBody.add(ProjectRisk);
    PanelBody.repaint();
    PanelBody.revalidate();
    }//GEN-LAST:event_BTN3MouseClicked

    private void BTN4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN4MouseClicked
    PanelBody.removeAll();
    PanelBody.repaint();
    PanelBody.revalidate();
    PanelBody.add(Request);
    PanelBody.repaint();
    PanelBody.revalidate();
    }//GEN-LAST:event_BTN4MouseClicked

    private void BTN5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN5MouseClicked
    PanelBody.removeAll();
    PanelBody.repaint();
    PanelBody.revalidate();
    PanelBody.add(Receiveditem);
    PanelBody.repaint();
    PanelBody.revalidate();
    }//GEN-LAST:event_BTN5MouseClicked
    public void setforeground(JLabel label){
        label.setForeground(Color.white);
    }
    public void resetForegound(JLabel label){
        label.setForeground(new Color(204,204,204));
    }
    private void BTN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN1MouseEntered
        setforeground(jLabel2);
        jLabel2.setFont(new java.awt.Font("Century Gothic Bold", 0, 18));
    }//GEN-LAST:event_BTN1MouseEntered

    private void BTN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN1MouseExited
        resetForegound(jLabel2);
        jLabel2.setFont(new java.awt.Font("Century Gothic Bold", 0, 14));
    }//GEN-LAST:event_BTN1MouseExited

    private void BTN2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN2MouseEntered
        setforeground(jLabel3);
        jLabel3.setFont(new java.awt.Font("Century Gothic Bold", 0, 18));
    }//GEN-LAST:event_BTN2MouseEntered

    private void BTN2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN2MouseExited
        resetForegound(jLabel3);
        jLabel3.setFont(new java.awt.Font("Century Gothic Bold", 0, 14));
    }//GEN-LAST:event_BTN2MouseExited

    private void BTN3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN3MouseEntered
        setforeground(jLabel4);
        jLabel4.setFont(new java.awt.Font("Century Gothic Bold", 0, 18));
    }//GEN-LAST:event_BTN3MouseEntered

    private void BTN3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN3MouseExited
        resetForegound(jLabel4);
        jLabel4.setFont(new java.awt.Font("Century Gothic Bold", 0, 14));
    }//GEN-LAST:event_BTN3MouseExited

    private void BTN4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN4MouseEntered
        setforeground(jLabel5);
        jLabel5.setFont(new java.awt.Font("Century Gothic Bold", 0, 18));
    }//GEN-LAST:event_BTN4MouseEntered

    private void BTN4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN4MouseExited
        resetForegound(jLabel5);
        jLabel5.setFont(new java.awt.Font("Century Gothic Bold", 0, 14));
    }//GEN-LAST:event_BTN4MouseExited

    private void BTN5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN5MouseEntered
        setforeground(jLabel6);
        jLabel6.setFont(new java.awt.Font("Century Gothic Bold", 0, 18));
    }//GEN-LAST:event_BTN5MouseEntered

    private void BTN5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN5MouseExited
        resetForegound(jLabel6);
        jLabel6.setFont(new java.awt.Font("Century Gothic Bold", 0, 14));
    }//GEN-LAST:event_BTN5MouseExited

    private void jButton_addriskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addriskActionPerformed
     Features.PM_AddRisk PM = new Features.PM_AddRisk();
     PM.setVisible(true);
    }//GEN-LAST:event_jButton_addriskActionPerformed

    private void manageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageActionPerformed
    Features.PM_Manage_Risk PM = new Features.PM_Manage_Risk();
    PM.setVisible(true);
    }//GEN-LAST:event_manageActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     Features.PM_AddNew_Project s = new Features.PM_AddNew_Project();
     s.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
    jButton6.setFont(new java.awt.Font("Century Gothic Bold", 1, 14));
    jButton6.setForeground(Color.white);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
          jButton6.setFont(new java.awt.Font("Century Gothic", 1, 12));
          jButton6.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseEntered
          jButton12.setFont(new java.awt.Font("Century Gothic Bold", 1, 14));
          jButton12.setForeground(Color.white);
    }//GEN-LAST:event_jButton12MouseEntered

    private void jButton12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseExited
          jButton12.setFont(new java.awt.Font("Century Gothic", 1, 12));
          jButton12.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_jButton12MouseExited

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     Features.PM_ManageProject m = new Features.PM_ManageProject();
     m.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
            jPanelSlider1.nextPanel(30, Ware, jPanelSlider1.left);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
             jPanelSlider1.nextPanel(30, Finance, jPanelSlider1.left);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
            jPanelSlider1.nextPanel(30, Vendor, jPanelSlider1.left);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
          jPanelSlider1.nextPanel(30, Legal, jPanelSlider1.left);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
           try{
           String sql = "SELECT * FROM Log1_project WHERE projectid LIKE '%"+Search.getText()+"%' ";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable_ProjectList.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
      
    }//GEN-LAST:event_SearchKeyReleased

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
     Features.PM_RequestMaterials m = new Features.PM_RequestMaterials();
     m.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
       Features.PM_RequestBudget b = new Features.PM_RequestBudget();
       b.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
       Features.PM_RequestContract x = new Features.PM_RequestContract();
       x.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        Features.PM_RequestContractor q = new Features.PM_RequestContractor();
        q.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         MessageFormat header = new MessageFormat("Report");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try{
            jTable2.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jPanelSlider1.nextPanel(30, Warehouse, jPanelSlider1.left);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
        int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){  
        try {
            String sql = "INSERT INTO log1_projecttimeline "
            + "(project_name, priority, project_description, task_name, start, end_task)"
            + "VALUES (?,?,?,?,?,?)";

            pst=conn.prepareStatement(sql);
            pst.setString(1,projectname.getText());
            pst.setString(2,priority.getText());
            pst.setString(3,jTextArea1.getText());
            pst.setString(4,taskname.getText());
            pst.setString(5, ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            pst.setString(6, ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText());
            pst.executeUpdate();  
            projecttimeline();
           
            
            JOptionPane.showMessageDialog(null, "Add Successfull! ");   
            
            projectname.setText("");
            priority.setText("");
            jTextArea1.setText("");
            ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText("");
            ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText("");
           
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }   
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void projectnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectnameKeyReleased
    try{
          String sql = "select * from log1_project where projectname=?";
          pst=conn.prepareCall(sql);
          pst.setString(1,projectname.getText());
          rs = pst.executeQuery();
           
  if(rs.next()) { 
       priority.setText(rs.getString("priority"));
       jTextArea1.setText(rs.getString("projectdescription"));
    }else{   
       priority.setText("");
       jTextArea1.setText("");
    }       
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_projectnameKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BTN1;
    private javax.swing.JPanel BTN2;
    private javax.swing.JPanel BTN3;
    private javax.swing.JPanel BTN4;
    private javax.swing.JPanel BTN5;
    private javax.swing.JPanel Finance;
    private javax.swing.JPanel Legal;
    private javax.swing.JPanel PN1;
    private javax.swing.JPanel PN2;
    private javax.swing.JPanel PN3;
    private javax.swing.JPanel PN4;
    private javax.swing.JPanel PN5;
    private javax.swing.JPanel PanelBody;
    private javax.swing.JPanel ProjectList;
    private javax.swing.JPanel ProjectRisk;
    private javax.swing.JPanel ProjectTimeline;
    private javax.swing.JPanel Receiveditem;
    private javax.swing.JPanel Request;
    private javax.swing.JTextField Search;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel Vendor;
    private javax.swing.JPanel Ware;
    private javax.swing.JPanel Warehouse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_addrisk;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public static final javax.swing.JTable jTable1 = new javax.swing.JTable();
    public static final javax.swing.JTable jTable2 = new javax.swing.JTable();
    public static final javax.swing.JTable jTable4 = new javax.swing.JTable();
    public static final javax.swing.JTable jTable5 = new javax.swing.JTable();
    public static final javax.swing.JTable jTable6 = new javax.swing.JTable();
    public static final javax.swing.JTable jTable_Budget = new javax.swing.JTable();
    public static final javax.swing.JTable jTable_ProjectList = new javax.swing.JTable();
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton manage;
    private javax.swing.JTextField priority;
    private javax.swing.JTextField projectname;
    public static final javax.swing.JTable tablerisk = new javax.swing.JTable();
    private javax.swing.JTextField taskname;
    // End of variables declaration//GEN-END:variables
}
